SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS pix_payments (
  id CHAR(36) NOT NULL,
  church_id CHAR(36) NOT NULL,
  congregation_id CHAR(36) NULL,
  member_id CHAR(36) NULL,
  phone VARCHAR(40) NOT NULL,
  name VARCHAR(255) NULL,
  amount DECIMAL(12,2) NOT NULL,
  payment_type VARCHAR(80) NOT NULL DEFAULT 'oferta',
  reference_id VARCHAR(190) NULL,
  external_id VARCHAR(190) NULL,
  qr_code LONGTEXT NULL,
  qr_code_base64 LONGTEXT NULL,
  copy_paste LONGTEXT NULL,
  status ENUM('pending','confirmed','failed','cancelled') NOT NULL DEFAULT 'pending',
  paid_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_pix_reference (reference_id),
  KEY idx_pix_church_status (church_id,status),
  KEY idx_pix_member (member_id),
  CONSTRAINT fk_pix_church FOREIGN KEY (church_id) REFERENCES churches(id) ON DELETE CASCADE,
  CONSTRAINT fk_pix_congregation FOREIGN KEY (congregation_id) REFERENCES congregations(id) ON DELETE SET NULL,
  CONSTRAINT fk_pix_member FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS service_types (
  id CHAR(36) NOT NULL,
  church_id CHAR(36) NOT NULL,
  congregation_id CHAR(36) NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NULL,
  day_of_week TINYINT NULL,
  week_of_month TINYINT NULL,
  time TIME NULL,
  is_recurring TINYINT(1) NOT NULL DEFAULT 1,
  poster_url TEXT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_service_types_church (church_id),
  KEY idx_service_types_congregation (congregation_id),
  CONSTRAINT fk_service_types_church FOREIGN KEY (church_id) REFERENCES churches(id) ON DELETE CASCADE,
  CONSTRAINT fk_service_types_congregation FOREIGN KEY (congregation_id) REFERENCES congregations(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS events (
  id CHAR(36) NOT NULL,
  church_id CHAR(36) NOT NULL,
  congregation_id CHAR(36) NULL,
  service_type_id CHAR(36) NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  theme VARCHAR(255) NULL,
  event_type VARCHAR(100) NULL,
  event_date DATETIME NOT NULL,
  end_date DATE NULL,
  location VARCHAR(255) NULL,
  image_url TEXT NULL,
  poster_url TEXT NULL,
  speaker_name VARCHAR(255) NULL,
  speaker_photo_url TEXT NULL,
  capacity INT NULL,
  registration_type VARCHAR(80) NOT NULL DEFAULT 'simple',
  reminder_sent TINYINT(1) NOT NULL DEFAULT 0,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_events_church_date (church_id,event_date),
  KEY idx_events_congregation (congregation_id),
  CONSTRAINT fk_events_church FOREIGN KEY (church_id) REFERENCES churches(id) ON DELETE CASCADE,
  CONSTRAINT fk_events_congregation FOREIGN KEY (congregation_id) REFERENCES congregations(id) ON DELETE SET NULL,
  CONSTRAINT fk_events_service_type FOREIGN KEY (service_type_id) REFERENCES service_types(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS event_sessions (
  id CHAR(36) NOT NULL,
  church_id CHAR(36) NOT NULL,
  event_id CHAR(36) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  session_date DATE NOT NULL,
  session_time TIME NOT NULL,
  duration_minutes INT NULL,
  speaker_name VARCHAR(255) NULL,
  speaker_photo_url TEXT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_event_sessions_event (event_id,session_date,session_time),
  CONSTRAINT fk_event_sessions_church FOREIGN KEY (church_id) REFERENCES churches(id) ON DELETE CASCADE,
  CONSTRAINT fk_event_sessions_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS event_registrations (
  id CHAR(36) NOT NULL,
  church_id CHAR(36) NOT NULL,
  event_id CHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(40) NOT NULL,
  email VARCHAR(190) NULL,
  birth_date DATE NULL,
  cpf VARCHAR(30) NULL,
  rg VARCHAR(30) NULL,
  cep VARCHAR(20) NULL,
  address_street VARCHAR(255) NULL,
  address_number VARCHAR(50) NULL,
  address_neighborhood VARCHAR(255) NULL,
  address_city VARCHAR(255) NULL,
  address_state VARCHAR(80) NULL,
  guests_count INT NOT NULL DEFAULT 0,
  guests_names JSON NULL,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_event_registrations_event (event_id),
  KEY idx_event_registrations_church (church_id),
  KEY idx_event_registrations_phone (phone),
  CONSTRAINT fk_event_registrations_church FOREIGN KEY (church_id) REFERENCES churches(id) ON DELETE CASCADE,
  CONSTRAINT fk_event_registrations_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;
