<?php
declare(strict_types=1);

function finance_public_handle(string $route): void {
    if($route!=='transparency-public')return;
    $token=(string)($_GET['token']??'');
    if(!preg_match('/^[a-f0-9]{48}$/',$token)){http_response_code(404);exit('Relatório não encontrado.');}
    $row=one("SELECT tp.*,c.name church_name,c.city,c.state FROM transparency_publications tp JOIN churches c ON c.id=tp.church_id WHERE tp.token=? AND tp.active=1",[$token]);
    if(!$row){http_response_code(404);exit('Relatório não encontrado ou publicação encerrada.');}
    $s=json_decode((string)$row['snapshot_json'],true);if(!is_array($s)){http_response_code(500);exit('Relatório indisponível.');}
    $tot=$s['totals']??[];$income=(float)($tot['income']??0);$expense=(float)($tot['expense']??0);$closing=(float)($tot['closing']??($income-$expense));
    $fmt=fn(float $v)=>'R$ '.number_format($v,2,',','.');
    $date=fn(string $d)=>($t=strtotime($d))?date('d/m/Y',$t):$d;
    $church=$s['church']??[];
    echo '<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>Transparência - '.htmlspecialchars((string)($church['name']??$row['church_name']),ENT_QUOTES,'UTF-8').'</title><style>
    :root{--nav:#0f3554;--blue:#1769d2;--green:#138a55;--red:#c94751;--ink:#172333;--muted:#718096;--line:#dde6ef;--bg:#f4f7fb}
    *{box-sizing:border-box}body{margin:0;font-family:Inter,Segoe UI,Arial,sans-serif;background:var(--bg);color:var(--ink)}.wrap{width:min(1050px,calc(100% - 28px));margin:auto}.top{background:linear-gradient(135deg,#0f3554,#1769d2);color:#fff;padding:38px 0}.brand{display:flex;justify-content:space-between;gap:30px;align-items:flex-start}.brand h1{margin:0;font-size:30px}.brand p{margin:7px 0 0;color:#d5e8f6}.badge{background:rgba(255,255,255,.13);border:1px solid rgba(255,255,255,.18);padding:9px 12px;border-radius:999px;font-size:12px;font-weight:800}.content{padding:28px 0 50px}.notice{background:#eef6fc;border:1px solid #d5e8f6;border-radius:14px;padding:14px 16px;color:#42627b;font-size:12px;margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:18px;box-shadow:0 5px 16px rgba(19,54,81,.05)}.card small{color:var(--muted);font-size:11px}.card strong{display:block;font-size:24px;margin-top:8px}.green{color:var(--green)}.red{color:var(--red)}.section{margin-top:22px}.section h2{font-size:17px;margin:0 0 11px}.table{width:100%;border-collapse:collapse;background:#fff;border:1px solid var(--line);border-radius:14px;overflow:hidden}.table th,.table td{padding:11px 12px;border-bottom:1px solid #e7edf3;text-align:left;font-size:12px}.table th{background:#f6f8fb;font-size:10px;color:#697c8d}.table td:last-child,.table th:last-child{text-align:right}.need-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.need{background:#fff;border:1px solid var(--line);border-radius:14px;padding:15px}.need b{display:block;font-size:13px}.need p{font-size:11px;color:#6e8091}.need span{font-size:11px;font-weight:800;color:#315c7b}.actions{display:flex;justify-content:flex-end;margin:20px 0}.print{border:0;background:#1769d2;color:#fff;padding:11px 16px;border-radius:10px;font-weight:800;cursor:pointer}.foot{text-align:center;color:#7c8b98;font-size:10px;padding:24px}.budget{height:10px;border-radius:999px;background:#edf2f6;overflow:hidden;margin-top:10px}.budget i{display:block;height:100%;background:linear-gradient(90deg,#1769d2,#36a0ef)}@media(max-width:760px){.brand{flex-direction:column}.grid{grid-template-columns:1fr 1fr}.need-grid{grid-template-columns:1fr}.brand h1{font-size:24px}}@media print{.actions{display:none}.top{padding:20px 0}.content{padding-top:16px}.card,.table,.need{box-shadow:none}}
    </style></head><body>';
    echo '<header class="top"><div class="wrap brand"><div><div style="font-size:12px;font-weight:900;letter-spacing:.12em;color:#9ed1f7">PORTAL DE TRANSPARÊNCIA</div><h1>'.htmlspecialchars((string)($church['name']??$row['church_name']),ENT_QUOTES,'UTF-8').'</h1><p>'.htmlspecialchars((string)$row['title'],ENT_QUOTES,'UTF-8').' · '.$date((string)$row['period_from']).' a '.$date((string)$row['period_to']).'</p></div><span class="badge">Prestação de contas publicada</span></div></header>';
    echo '<main class="content"><div class="wrap"><div class="notice">Este portal apresenta informações financeiras <b>consolidadas</b>. Nomes de dizimistas, doadores, dados bancários e comprovantes particulares não são publicados.</div><div class="actions"><button class="print" onclick="window.print()">Imprimir prestação de contas</button></div>';
    echo '<div class="grid"><div class="card"><small>Saldo inicial</small><strong>'.$fmt((float)($tot['opening']??0)).'</strong></div><div class="card"><small>Entradas</small><strong class="green">'.$fmt($income).'</strong></div><div class="card"><small>Saídas</small><strong class="red">'.$fmt($expense).'</strong></div><div class="card"><small>Saldo final</small><strong>'.$fmt($closing).'</strong></div></div>';
    echo '<section class="section"><h2>Movimentação por categoria</h2><table class="table"><thead><tr><th>TIPO</th><th>CATEGORIA</th><th>VALOR</th></tr></thead><tbody>';
    foreach(($s['categories']??[]) as $c){$dir=(string)($c['direction']??'expense');echo '<tr><td>'.($dir==='income'?'Entrada':'Saída').'</td><td>'.htmlspecialchars((string)$c['name'],ENT_QUOTES,'UTF-8').'</td><td class="'.($dir==='income'?'green':'red').'">'.$fmt((float)$c['total']).'</td></tr>';}
    echo '</tbody></table></section>';
    if(!empty($s['funds'])){echo '<section class="section"><h2>Fundos e projetos</h2><table class="table"><thead><tr><th>FUNDO / DESTINAÇÃO</th><th>ENTRADAS</th><th>SAÍDAS</th></tr></thead><tbody>';foreach($s['funds'] as $f)echo '<tr><td>'.htmlspecialchars((string)$f['name'],ENT_QUOTES,'UTF-8').'</td><td class="green">'.$fmt((float)$f['income']).'</td><td class="red">'.$fmt((float)$f['expense']).'</td></tr>';echo '</tbody></table></section>';}
    $bp=(float)($s['budget']['planned']??0);$ba=(float)($s['budget']['actual']??0);if($bp>0){$pct=min(100,max(0,($ba/$bp)*100));echo '<section class="section"><h2>Orçamento de despesas</h2><div class="card"><small>Previsto x realizado</small><strong>'.$fmt($ba).' de '.$fmt($bp).'</strong><div class="budget"><i style="width:'.number_format($pct,1,'.','').'%"></i></div><p style="font-size:11px;color:#718096">'.number_format($pct,1,',','.').'% do orçamento utilizado no período.</p></div></section>';}
    if(!empty($s['needs'])){echo '<section class="section"><h2>Necessidades e projetos em acompanhamento</h2><div class="need-grid">';foreach($s['needs'] as $n){echo '<div class="need"><b>'.htmlspecialchars((string)$n['title'],ENT_QUOTES,'UTF-8').'</b><p>'.htmlspecialchars((string)($n['description']??''),ENT_QUOTES,'UTF-8').'</p><span>Estimativa: '.$fmt((float)$n['estimated_amount']).' · '.htmlspecialchars((string)$n['status'],ENT_QUOTES,'UTF-8').'</span></div>';}echo '</div></section>';}
    echo '<div class="foot">Publicado em '.htmlspecialchars((string)$row['published_at'],ENT_QUOTES,'UTF-8').' · AdminIgreja</div></div></main></body></html>';exit;
}
