<?php
declare(strict_types=1);

function finance_pro_guard(): void {
    if(!can_treasury()){http_response_code(403);exit('Acesso restrito à Tesouraria.');}
}
function finance_status_label(string $status): string {
    return ['open'=>'Em aberto','paid'=>'Pago','cancelled'=>'Cancelado','pending'=>'Pendente','posted'=>'Lançado','skipped'=>'Ignorado','matched'=>'Conciliado','ignored'=>'Ignorado','closed'=>'Fechado','reopened'=>'Reaberto','requested'=>'Solicitado','approved'=>'Aprovado','purchased'=>'Comprado'][$status]??$status;
}
function finance_month_label(string $month): string {
    [$f]=finance_month_bounds($month);$months=[1=>'janeiro',2=>'fevereiro',3=>'março',4=>'abril',5=>'maio',6=>'junho',7=>'julho',8=>'agosto',9=>'setembro',10=>'outubro',11=>'novembro',12=>'dezembro'];
    return $months[(int)substr($f,5,2)].' de '.substr($f,0,4);
}
function finance_prefill_from_sources(int $cid): array {
    $p=['direction'=>'expense','income_kind'=>'other','amount'=>'','date'=>date('Y-m-d'),'description'=>'','category_id'=>0,'account_id'=>0,'fund_id'=>0,'cost_center_id'=>0,'supplier'=>'','payment_method'=>'','document_number'=>'','member_id'=>0,'occurrence_id'=>0,'bank_line_id'=>0];
    $occ=(int)($_GET['occurrence']??0);
    if($occ){
        $r=one("SELECT o.id occurrence_id,o.due_date,r.* FROM recurring_occurrences o JOIN recurring_financial_items r ON r.id=o.recurring_id WHERE o.id=? AND o.church_id=? AND o.status='pending'",[$occ,$cid]);
        if($r)$p=array_merge($p,['direction'=>$r['direction'],'income_kind'=>$r['income_kind']?:'other','amount'=>(string)$r['amount'],'date'=>$r['due_date'],'description'=>$r['description'],'category_id'=>(int)$r['category_id'],'account_id'=>(int)$r['account_id'],'fund_id'=>(int)$r['fund_id'],'cost_center_id'=>(int)$r['cost_center_id'],'supplier'=>(string)($r['supplier']??''),'occurrence_id'=>(int)$r['occurrence_id']]);
    }
    $bank=(int)($_GET['bank_line']??0);
    if($bank){
        $r=one("SELECT * FROM bank_statement_lines WHERE id=? AND church_id=? AND status='pending'",[$bank,$cid]);
        if($r)$p=array_merge($p,['direction'=>(float)$r['amount']>=0?'income':'expense','amount'=>(string)abs((float)$r['amount']),'date'=>$r['transaction_date'],'description'=>$r['description'],'account_id'=>(int)$r['account_id'],'bank_line_id'=>(int)$r['id']]);
    }
    $kind=(string)($_GET['kind']??'');
    if(in_array($kind,['tithe','offering','donation','expense','income'],true)){
        if($kind==='expense')$p['direction']='expense';
        elseif($kind==='income')$p['direction']='income';
        else{$p['direction']='income';$p['income_kind']=$kind;}
    }
    return $p;
}

function finance_route_treasury(int $cid): never {
    finance_pro_guard();finance_seed_defaults($cid);finance_ensure_occurrences($cid);
    [$from,$to,$month]=finance_month_bounds(date('Y-m'));
    $tot=finance_period_totals($cid,$from,$to);$p=finance_pending_summary($cid,$month);
    $recent=all("SELECT t.*,a.name account_name FROM transactions t LEFT JOIN accounts a ON a.id=t.account_id WHERE t.church_id=? ORDER BY t.transaction_date DESC,t.id DESC LIMIT 8",[$cid]);
    $needs=(int)(one("SELECT COUNT(*) c FROM church_needs WHERE church_id=? AND status IN ('requested','approved')",[$cid])['c']??0);
    page_top('Tesouraria','Painel de conferência · o que entrou, saiu e ainda falta fazer');flash();
    echo '<div class="treasury-hero"><div><span class="eyebrow-app">TESOURARIA PROFISSIONAL</span><h2>'.e(finance_month_label($month)).'</h2><p>Use este painel como checklist diário. Quando uma pendência aparecer aqui, ela ainda precisa de atenção.</p></div><a class="btn" href="/?r=finance">+ Novo lançamento</a></div>';
    echo '<div class="grid treasury-kpis"><div class="card metric"><small>Entradas do mês</small><strong class="money in">'.e(money_br((float)$tot['income'])).'</strong></div><div class="card metric"><small>Saídas do mês</small><strong class="money out">'.e(money_br((float)$tot['expense'])).'</strong></div><div class="card metric"><small>Saldo do mês</small><strong>'.e(money_br((float)$tot['income']-(float)$tot['expense'])).'</strong></div><div class="card metric"><small>Situação do mês</small><strong class="'.($p['closed']?'money in':'').'">'.($p['closed']?'Fechado':'Em conferência').'</strong></div></div>';

    $tasks=[
      ['Comprovantes faltando',(int)$p['missing_receipts'],'finance','Anexe o recibo das despesas para não esquecer depois.'],
      ['Extrato sem conciliar',(int)$p['bank_pending'],'reconciliation','Movimentações do banco ainda sem ligação com o sistema.'],
      ['Lançamentos recorrentes',(int)$p['recurring_pending'],'recurring','Contas mensais previstas que ainda não foram lançadas.'],
      ['Contas vencidas',(int)$p['overdue_payables'],'payables','Contas a pagar que chegaram ao vencimento e continuam abertas.'],
      ['Necessidades da igreja',$needs,'needs','Compras, reparos ou itens solicitados e ainda em acompanhamento.'],
    ];
    echo '<div class="dashboard-section"><div class="dashboard-section-head"><div><h3>O que falta fazer</h3><p>O objetivo é chegar ao fechamento do mês sem nenhuma pendência.</p></div></div><div class="treasury-tasks">';
    foreach($tasks as $t){$ok=$t[1]===0;echo '<a class="task-card '.($ok?'task-ok':'task-attention').'" href="/?r='.e($t[2]).'"><span class="task-count">'.(int)$t[1].'</span><span><b>'.e($t[0]).'</b><small>'.e($ok?'Tudo certo.':$t[3]).'</small></span><i>›</i></a>';}
    echo '</div></div>';

    echo '<div class="dashboard-section"><div class="dashboard-section-head"><div><h3>Ações rápidas</h3><p>Fluxos feitos para o tesoureiro não precisar procurar telas.</p></div></div><div class="quick-actions treasury-actions">';
    $quick=[['finance&kind=tithe','DÍZ','Lançar dízimo','Escolher membro e valor'],['finance&kind=offering','OF','Lançar oferta','Entrada do culto/campanha'],['finance&kind=expense','SAÍ','Registrar despesa','Pagamento com comprovante'],['payables','PAG','Conta a pagar','Cadastrar vencimento'],['reconciliation','BAN','Conciliar banco','Importar OFX ou CSV'],['closing','✓','Fechar mês','Checklist e conferência'],['budgets','ORÇ','Orçamento','Previsto x realizado'],['reports','PDF','Prestação de contas','Visualizar, imprimir e PDF']];
    foreach($quick as $q)echo '<a class="quick-action" href="/?r='.$q[0].'"><span class="quick-action-icon">'.$q[1].'</span><span><b>'.$q[2].'</b><small>'.$q[3].'</small></span></a>';
    echo '</div></div>';

    echo '<div class="dashboard-section"><div class="card"><div class="card-title-row"><div><h3>Últimas movimentações</h3><p class="muted">Confira se o que aconteceu no caixa/banco já está registrado.</p></div><a class="btn light" href="/?r=finance">Ver lançamentos</a></div><div class="table-wrap"><table class="table"><thead><tr><th>DATA</th><th>TIPO</th><th>DESCRIÇÃO</th><th>CONTA</th><th>VALOR</th></tr></thead><tbody>';
    if(!$recent)echo '<tr><td colspan="5">Nenhuma movimentação cadastrada.</td></tr>';
    foreach($recent as $r){$in=$r['direction']==='income';echo '<tr><td>'.e(br_date((string)$r['transaction_date'])).'</td><td>'.($in?'Entrada':'Saída').'</td><td>'.e($r['description']).'</td><td>'.e($r['account_name']??'—').'</td><td class="money '.($in?'in':'out').'">'.($in?'+ ':'- ').e(money_br((float)$r['amount'])).'</td></tr>';}
    echo '</tbody></table></div></div></div>';page_bottom();exit;
}

function finance_route_finance(int $cid): never {
    finance_pro_guard();finance_seed_defaults($cid);
    if($_SERVER['REQUEST_METHOD']==='POST'){
        verify_csrf();$action=(string)($_POST['action']??'create');
        try{
            if($action==='attach_receipt'){
                $id=(int)($_POST['transaction_id']??0);$tx=one("SELECT * FROM transactions WHERE id=? AND church_id=? AND status='posted'",[$id,$cid]);if(!$tx)throw new RuntimeException('Lançamento não encontrado.');
                if(empty($_FILES['receipt']))throw new RuntimeException('Selecione um comprovante.');
                $receipt=save_receipt_upload($cid,$_FILES['receipt']);
                q('UPDATE transactions SET receipt_path=?,receipt_name=?,receipt_mime=?,receipt_size=? WHERE id=? AND church_id=?',[$receipt['path'],$receipt['name'],$receipt['mime'],$receipt['size'],$id,$cid]);
                audit('attach_transaction_receipt','transaction',$id);set_flash('Comprovante anexado.');
            }elseif($action==='reverse'){
                $id=(int)($_POST['transaction_id']??0);$reason=trim((string)($_POST['reason']??''));$tx=one("SELECT * FROM transactions WHERE id=? AND church_id=? AND status='posted'",[$id,$cid]);
                if(!$tx)throw new RuntimeException('Lançamento não encontrado.');finance_assert_open_period($cid,(string)$tx['transaction_date']);
                if(strlen($reason)<5)throw new RuntimeException('Informe o motivo do estorno.');
                q("UPDATE transactions SET status='cancelled',reversed_at=NOW(),reversed_by=?,reversal_reason=? WHERE id=? AND church_id=?",[(int)user()['id'],$reason,$id,$cid]);
                if(!empty($tx['bank_line_id']))q("UPDATE bank_statement_lines SET status='pending',matched_transaction_id=NULL,resolved_at=NULL WHERE id=? AND church_id=?",[(int)$tx['bank_line_id'],$cid]);
                audit('reverse_transaction','transaction',$id,['reason'=>$reason]);set_flash('Lançamento estornado sem apagar o histórico.');
            }else{
                $dir=in_array((string)($_POST['direction']??''),['income','expense'],true)?(string)$_POST['direction']:'expense';
                $kind=$dir==='income'?(string)($_POST['income_kind']??'other'):null;if($dir==='income'&&!in_array($kind,['tithe','offering','donation','other'],true))$kind='other';
                $date=(string)($_POST['transaction_date']??date('Y-m-d'));finance_assert_open_period($cid,$date);
                $amount=(float)($_POST['amount']??0);if($amount<=0)throw new RuntimeException('Informe um valor maior que zero.');
                $cat=finance_category($cid,(int)($_POST['category_id']??0));if(!$cat)throw new RuntimeException('Escolha a categoria.');
                if($cat['direction']!=='both'&&$cat['direction']!==$dir)throw new RuntimeException('A categoria escolhida não corresponde ao tipo de lançamento.');
                $memberId=null;if($dir==='income'&&$kind==='tithe'){$candidate=(int)($_POST['member_id']??0);$m=one("SELECT id FROM members WHERE id=? AND church_id=? AND status='active'",[$candidate,$cid]);if(!$m)throw new RuntimeException('Escolha o membro do dízimo.');$memberId=$candidate;}
                $receipt=null;if(!empty($_FILES['receipt']['name']))$receipt=save_receipt_upload($cid,$_FILES['receipt']);
                $occ=(int)($_POST['occurrence_id']??0);$bank=(int)($_POST['bank_line_id']??0);
                q("INSERT INTO transactions(church_id,account_id,member_id,direction,income_kind,category_id,category,fund_id,cost_center_id,description,supplier,payment_method,document_number,amount,transaction_date,created_by,receipt_path,receipt_name,receipt_mime,receipt_size,recurring_occurrence_id,bank_line_id)
                   VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[
                   $cid,(int)($_POST['account_id']??0)?:null,$memberId,$dir,$kind,(int)$cat['id'],$cat['name'],(int)($_POST['fund_id']??0)?:null,(int)($_POST['cost_center_id']??0)?:null,
                   trim((string)($_POST['description']??'')),trim((string)($_POST['supplier']??''))?:null,trim((string)($_POST['payment_method']??''))?:null,trim((string)($_POST['document_number']??''))?:null,
                   $amount,$date,(int)user()['id'],$receipt['path']??null,$receipt['name']??null,$receipt['mime']??null,$receipt['size']??null,$occ?:null,$bank?:null
                ]);
                $id=(int)db()->lastInsertId();
                if($occ)q("UPDATE recurring_occurrences SET status='posted',transaction_id=?,resolved_by=?,resolved_at=NOW() WHERE id=? AND church_id=?",[$id,(int)user()['id'],$occ,$cid]);
                if($bank)q("UPDATE bank_statement_lines SET status='matched',matched_transaction_id=?,resolved_at=NOW() WHERE id=? AND church_id=?",[$id,$bank,$cid]);
                audit('create_transaction','transaction',$id,['direction'=>$dir,'category'=>$cat['name'],'member_id'=>$memberId,'receipt'=>(bool)$receipt]);
                set_flash('Lançamento registrado'.($dir==='expense'&&!$receipt?' — lembrete: o comprovante ainda está pendente.':'.'));
            }
        }catch(Throwable $e){error_log('finance-pro: '.$e->getMessage());set_flash($e->getMessage(),'error');}
        redirect('/?r=finance');
    }

    $p=finance_prefill_from_sources($cid);$accounts=finance_accounts($cid);$cats=finance_categories($cid);$funds=finance_funds($cid);$centers=finance_cost_centers($cid);$members=all("SELECT id,name FROM members WHERE church_id=? AND status='active' ORDER BY name",[$cid]);
    $rows=all("SELECT t.*,a.name account_name,m.name member_name,f.name fund_name,cc.name cost_center_name FROM transactions t LEFT JOIN accounts a ON a.id=t.account_id LEFT JOIN members m ON m.id=t.member_id LEFT JOIN finance_funds f ON f.id=t.fund_id LEFT JOIN cost_centers cc ON cc.id=t.cost_center_id WHERE t.church_id=? ORDER BY t.transaction_date DESC,t.id DESC LIMIT 250",[$cid]);
    page_top('Lançamentos','Tesouraria · registro simples com classificação, comprovante e rastreabilidade');flash();
    echo '<div class="finance-choice"><a href="/?r=finance&kind=tithe"><b>Dízimo</b><small>Vinculado ao membro</small></a><a href="/?r=finance&kind=offering"><b>Oferta</b><small>Entrada coletiva</small></a><a href="/?r=finance&kind=donation"><b>Doação</b><small>Outra contribuição</small></a><a href="/?r=finance&kind=expense"><b>Despesa</b><small>Pagamento / compra</small></a><a href="/?r=finance&kind=income"><b>Outra entrada</b><small>Receita diversa</small></a></div>';
    echo '<div class="card"><div class="card-title-row"><div><h3>Novo lançamento</h3><p class="muted">Preencha o que aconteceu. O sistema organiza a classificação para relatórios e transparência.</p></div><a class="btn light" href="/?r=treasury">Voltar ao painel</a></div><form method="post" enctype="multipart/form-data" id="financeProForm">'.csrf_input().'<input type="hidden" name="action" value="create"><input type="hidden" name="occurrence_id" value="'.(int)$p['occurrence_id'].'"><input type="hidden" name="bank_line_id" value="'.(int)$p['bank_line_id'].'"><div class="form-grid">';
    echo '<div><label>Movimentação</label><select name="direction" id="fpDirection"><option value="income" '.($p['direction']==='income'?'selected':'').'>Entrada</option><option value="expense" '.($p['direction']==='expense'?'selected':'').'>Saída / despesa</option></select></div><div id="fpKindBox"><label>Tipo da entrada</label><select name="income_kind" id="fpKind"><option value="other" '.($p['income_kind']==='other'?'selected':'').'>Outra entrada</option><option value="tithe" '.($p['income_kind']==='tithe'?'selected':'').'>Dízimo</option><option value="offering" '.($p['income_kind']==='offering'?'selected':'').'>Oferta</option><option value="donation" '.($p['income_kind']==='donation'?'selected':'').'>Doação</option></select></div>';
    echo '<div id="fpMemberBox"><label>Membro do dízimo</label><select name="member_id"><option value="">Selecione...</option>';foreach($members as $m)echo '<option value="'.(int)$m['id'].'">'.e($m['name']).'</option>';echo '</select></div>';
    echo '<div><label>Categoria</label><select name="category_id" id="fpCategory" required><option value="">Selecione...</option>';foreach($cats as $c)echo '<option data-direction="'.e($c['direction']).'" value="'.(int)$c['id'].'" '.((int)$p['category_id']===(int)$c['id']?'selected':'').'>'.e(($c['accounting_code']?$c['accounting_code'].' · ':'').$c['name']).'</option>';echo '</select></div>';
    echo '<div><label>Valor</label><input name="amount" type="number" min="0.01" step="0.01" value="'.e($p['amount']).'" required></div><div><label>Data</label><input name="transaction_date" type="date" value="'.e($p['date']).'" required></div>';
    echo '<div><label>Conta / caixa</label><select name="account_id"><option value="">Não informado</option>';foreach($accounts as $a)echo '<option value="'.(int)$a['id'].'" '.((int)$p['account_id']===(int)$a['id']?'selected':'').'>'.e($a['name']).'</option>';echo '</select></div>';
    echo '<div><label>Fundo / destinação</label><select name="fund_id"><option value="">Fundo Geral / não informado</option>';foreach($funds as $f)echo '<option value="'.(int)$f['id'].'" '.((int)$p['fund_id']===(int)$f['id']?'selected':'').'>'.e($f['name']).($f['restricted']?' · restrito':'').'</option>';echo '</select></div>';
    echo '<div><label>Centro de custo</label><select name="cost_center_id"><option value="">Não informado</option>';foreach($centers as $c)echo '<option value="'.(int)$c['id'].'" '.((int)$p['cost_center_id']===(int)$c['id']?'selected':'').'>'.e($c['name']).'</option>';echo '</select></div>';
    echo '<div id="fpSupplier"><label>Fornecedor / favorecido</label><input name="supplier" value="'.e($p['supplier']).'" placeholder="Quem recebeu o pagamento"></div><div><label>Forma de pagamento</label><select name="payment_method"><option value="">Não informado</option><option>Dinheiro</option><option>PIX</option><option>Transferência</option><option>Cartão</option><option>Boleto</option><option>Débito automático</option><option>Cheque</option></select></div><div><label>Nº documento / NF / recibo</label><input name="document_number" value="'.e($p['document_number']).'"></div>';
    echo '<div class="full"><label>Descrição / histórico</label><input name="description" value="'.e($p['description']).'" required placeholder="Ex.: pagamento da energia do templo"></div><div class="full"><label>Comprovante <span class="optional">(recomendado para despesas)</span></label><input type="file" name="receipt" accept="application/pdf,image/jpeg,image/png,image/webp"><small class="hint">Pode anexar agora ou depois. O painel da Tesouraria avisa quando uma despesa está sem comprovante.</small></div></div><p><button class="btn">Salvar lançamento</button></p></form></div>';
    echo '<script>(function(){const d=document.getElementById("fpDirection"),k=document.getElementById("fpKind"),kb=document.getElementById("fpKindBox"),mb=document.getElementById("fpMemberBox"),sup=document.getElementById("fpSupplier"),cat=document.getElementById("fpCategory");function sync(){const inc=d.value==="income";kb.hidden=!inc;mb.hidden=!(inc&&k.value==="tithe");sup.hidden=inc;Array.from(cat.options).forEach(o=>{if(!o.value)return;o.hidden=!(o.dataset.direction==="both"||o.dataset.direction===d.value)});if(cat.selectedOptions[0]&&cat.selectedOptions[0].hidden)cat.value="";}d.addEventListener("change",sync);k.addEventListener("change",sync);sync()})();</script>';

    echo '<br><div class="card"><div class="card-title-row"><div><h3>Histórico financeiro</h3><p class="muted">Nada é apagado: estornos permanecem registrados para auditoria.</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>DATA</th><th>TIPO</th><th>CATEGORIA</th><th>HISTÓRICO</th><th>FUNDO</th><th>COMPROVANTE</th><th>VALOR</th><th>AÇÃO</th></tr></thead><tbody>';
    foreach($rows as $r){$in=$r['direction']==='income';$cancel=$r['status']==='cancelled';echo '<tr class="'.($cancel?'row-cancelled':'').'"><td>'.e(br_date((string)$r['transaction_date'])).'</td><td>'.($in?'Entrada':'Saída').($cancel?' · ESTORNADO':'').'</td><td>'.e($r['category']).'</td><td>'.e($r['description']).'</td><td>'.e($r['fund_name']??'—').'</td><td>';if($r['receipt_path'])echo '<a class="receipt-link" target="_blank" href="/?r=receipt&id='.(int)$r['id'].'">Ver comprovante</a>';elseif(!$cancel&& !$in)echo '<form class="inline-upload" method="post" enctype="multipart/form-data">'.csrf_input().'<input type="hidden" name="action" value="attach_receipt"><input type="hidden" name="transaction_id" value="'.(int)$r['id'].'"><input type="file" name="receipt" accept="application/pdf,image/jpeg,image/png,image/webp" required><button class="btn light">Anexar</button></form>';else echo '—';echo '</td><td class="money '.($in?'in':'out').'">'.($in?'+ ':'- ').e(money_br((float)$r['amount'])).'</td><td>';if(!$cancel)echo '<details class="reverse-box"><summary>Estornar</summary><form method="post">'.csrf_input().'<input type="hidden" name="action" value="reverse"><input type="hidden" name="transaction_id" value="'.(int)$r['id'].'"><input name="reason" placeholder="Motivo do estorno" required><button class="btn danger">Confirmar</button></form></details>';else echo '<span class="pill">Histórico preservado</span>';echo '</td></tr>';}
    echo '</tbody></table></div></div>';page_bottom();exit;
}

function finance_route_payables(int $cid): never {
    finance_pro_guard();finance_seed_defaults($cid);
    if($_SERVER['REQUEST_METHOD']==='POST'){
        verify_csrf();$action=(string)($_POST['action']??'create');
        try{
            if($action==='create'){
                $amount=(float)($_POST['amount']??0);if($amount<=0)throw new RuntimeException('Informe o valor.');
                q("INSERT INTO payables(church_id,supplier,description,category,amount,due_date,account_id,fund_id,cost_center_id,status) VALUES(?,?,?,?,?,?,?,?,?,'open')",[$cid,trim((string)$_POST['supplier']),trim((string)$_POST['description']),trim((string)($_POST['category']??'')),$amount,$_POST['due_date'],(int)($_POST['account_id']??0)?:null,(int)($_POST['fund_id']??0)?:null,(int)($_POST['cost_center_id']??0)?:null]);audit('create_payable','payable',(int)db()->lastInsertId());set_flash('Conta a pagar cadastrada. Ela aparecerá nas pendências até ser paga.');
            }elseif($action==='pay'){
                $id=(int)($_POST['payable_id']??0);$p=one("SELECT * FROM payables WHERE id=? AND church_id=? AND status='open'",[$id,$cid]);if(!$p)throw new RuntimeException('Conta não encontrada ou já resolvida.');
                $date=(string)($_POST['paid_at']??date('Y-m-d'));finance_assert_open_period($cid,$date);
                $cat=one("SELECT * FROM finance_categories WHERE church_id=? AND direction='expense' AND name=? LIMIT 1",[$cid,(string)$p['category']]);if(!$cat)$cat=one("SELECT * FROM finance_categories WHERE church_id=? AND direction='expense' ORDER BY id LIMIT 1",[$cid]);
                $receipt=null;if(!empty($_FILES['receipt']['name']))$receipt=save_receipt_upload($cid,$_FILES['receipt']);
                q("INSERT INTO transactions(church_id,account_id,direction,category_id,category,fund_id,cost_center_id,description,supplier,payment_method,amount,transaction_date,created_by,receipt_path,receipt_name,receipt_mime,receipt_size) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[$cid,(int)($_POST['account_id']??$p['account_id'])?:null,'expense',(int)($cat['id']??0)?:null,(string)($p['category']?:($cat['name']??'Despesa')),(int)$p['fund_id']?:null,(int)$p['cost_center_id']?:null,(string)$p['description'],(string)$p['supplier'],trim((string)($_POST['payment_method']??''))?:null,(float)$p['amount'],$date,(int)user()['id'],$receipt['path']??null,$receipt['name']??null,$receipt['mime']??null,$receipt['size']??null]);
                $tx=(int)db()->lastInsertId();q("UPDATE payables SET status='paid',paid_at=?,paid_transaction_id=? WHERE id=? AND church_id=?",[$date,$tx,$id,$cid]);audit('pay_payable','payable',$id,['transaction_id'=>$tx]);set_flash('Pagamento registrado e vinculado ao financeiro.');
            }elseif($action==='cancel'){
                $id=(int)($_POST['payable_id']??0);q("UPDATE payables SET status='cancelled' WHERE id=? AND church_id=? AND status='open'",[$id,$cid]);audit('cancel_payable','payable',$id);set_flash('Conta cancelada.');
            }
        }catch(Throwable $e){set_flash($e->getMessage(),'error');}
        redirect('/?r=payables');
    }
    $rows=all("SELECT p.*,a.name account_name,f.name fund_name,c.name cost_center_name FROM payables p LEFT JOIN accounts a ON a.id=p.account_id LEFT JOIN finance_funds f ON f.id=p.fund_id LEFT JOIN cost_centers c ON c.id=p.cost_center_id WHERE p.church_id=? ORDER BY FIELD(p.status,'open','paid','cancelled'),p.due_date,p.id DESC",[$cid]);
    $accounts=finance_accounts($cid);$funds=finance_funds($cid);$centers=finance_cost_centers($cid);$expenseCats=finance_categories($cid,'expense');
    page_top('Contas a pagar','Cadastre antes do vencimento para o sistema lembrar você');flash();
    echo '<div class="card"><div class="card-title-row"><div><h3>Nova conta</h3><p class="muted">Energia, água, aluguel, serviços e qualquer compromisso futuro devem entrar aqui assim que forem conhecidos.</p></div></div><form method="post">'.csrf_input().'<input type="hidden" name="action" value="create"><div class="form-grid"><div><label>Fornecedor</label><input name="supplier" required></div><div><label>Descrição</label><input name="description" required></div><div><label>Categoria</label><select name="category" required>';foreach($expenseCats as $c)echo '<option>'.e($c['name']).'</option>';echo '</select></div><div><label>Valor</label><input type="number" step="0.01" min="0.01" name="amount" required></div><div><label>Vencimento</label><input type="date" name="due_date" required></div><div><label>Conta prevista</label><select name="account_id"><option value="">Não definida</option>';foreach($accounts as $a)echo '<option value="'.(int)$a['id'].'">'.e($a['name']).'</option>';echo '</select></div><div><label>Fundo</label><select name="fund_id"><option value="">Não definido</option>';foreach($funds as $f)echo '<option value="'.(int)$f['id'].'">'.e($f['name']).'</option>';echo '</select></div><div><label>Centro de custo</label><select name="cost_center_id"><option value="">Não definido</option>';foreach($centers as $c)echo '<option value="'.(int)$c['id'].'">'.e($c['name']).'</option>';echo '</select></div></div><p><button class="btn">Cadastrar compromisso</button></p></form></div><br>';
    echo '<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>VENCIMENTO</th><th>FORNECEDOR</th><th>DESCRIÇÃO</th><th>VALOR</th><th>STATUS</th><th>AÇÃO</th></tr></thead><tbody>';
    foreach($rows as $r){
        $late=$r['status']==='open'&&$r['due_date']<date('Y-m-d');
        echo '<tr><td class="'.($late?'text-danger':'').'">'.e(br_date((string)$r['due_date'])).'</td><td>'.e($r['supplier']).'</td><td>'.e($r['description']).'</td><td>'.e(money_br((float)$r['amount'])).'</td><td><span class="pill">'.e(finance_status_label((string)$r['status'])).'</span></td><td>';
        if($r['status']==='open'){
            echo '<details class="pay-box"><summary class="btn green">Registrar pagamento</summary><form method="post" enctype="multipart/form-data">'.csrf_input().'<input type="hidden" name="action" value="pay"><input type="hidden" name="payable_id" value="'.(int)$r['id'].'"><label>Data do pagamento</label><input type="date" name="paid_at" value="'.date('Y-m-d').'" required><label>Conta</label><select name="account_id"><option value="">Selecione...</option>';
            foreach($accounts as $a)echo '<option value="'.(int)$a['id'].'">'.e($a['name']).'</option>';
            echo '</select><label>Forma</label><select name="payment_method"><option>PIX</option><option>Dinheiro</option><option>Transferência</option><option>Boleto</option><option>Débito automático</option><option>Cartão</option></select><label>Comprovante</label><input type="file" name="receipt" accept="application/pdf,image/jpeg,image/png,image/webp"><button class="btn">Pagar e lançar</button></form></details>';
        }else{
            echo '—';
        }
        echo '</td></tr>';
    }
    echo '</tbody></table></div></div>';page_bottom();exit;
}

function finance_route_recurring(int $cid): never {
    finance_pro_guard();finance_seed_defaults($cid);finance_ensure_occurrences($cid);
    if($_SERVER['REQUEST_METHOD']==='POST'){
        verify_csrf();$action=(string)($_POST['action']??'create');
        try{
            if($action==='create'){
                $dir=in_array((string)($_POST['direction']??''),['income','expense'],true)?(string)$_POST['direction']:'expense';$cat=finance_category($cid,(int)($_POST['category_id']??0));if(!$cat)throw new RuntimeException('Escolha a categoria.');
                q("INSERT INTO recurring_financial_items(church_id,direction,income_kind,category_id,category,description,supplier,amount,due_day,account_id,fund_id,cost_center_id,receipt_required,active,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,1,?)",[$cid,$dir,$dir==='income'?(string)($_POST['income_kind']??'other'):null,(int)$cat['id'],$cat['name'],trim((string)$_POST['description']),trim((string)($_POST['supplier']??''))?:null,(float)$_POST['amount'],max(1,min(31,(int)$_POST['due_day'])),(int)($_POST['account_id']??0)?:null,(int)($_POST['fund_id']??0)?:null,(int)($_POST['cost_center_id']??0)?:null,!empty($_POST['receipt_required'])?1:0,(int)user()['id']]);audit('create_recurring','recurring',(int)db()->lastInsertId());set_flash('Rotina mensal criada.');
            }elseif($action==='toggle'){$id=(int)$_POST['id'];q('UPDATE recurring_financial_items SET active=IF(active=1,0,1) WHERE id=? AND church_id=?',[$id,$cid]);audit('toggle_recurring','recurring',$id);set_flash('Rotina atualizada.');
            }elseif($action==='skip'){$id=(int)$_POST['occurrence_id'];q("UPDATE recurring_occurrences SET status='skipped',resolved_by=?,resolved_at=NOW(),note=? WHERE id=? AND church_id=? AND status='pending'",[(int)user()['id'],trim((string)($_POST['note']??'Ignorado neste mês')),$id,$cid]);audit('skip_recurring_occurrence','recurring_occurrence',$id);set_flash('Pendência marcada como não aplicável neste mês.');}
        }catch(Throwable $e){set_flash($e->getMessage(),'error');}
        redirect('/?r=recurring');
    }
    finance_ensure_occurrences($cid);$items=all('SELECT * FROM recurring_financial_items WHERE church_id=? ORDER BY active DESC,due_day,description',[$cid]);$occ=all("SELECT o.*,r.description,r.amount,r.direction,r.supplier FROM recurring_occurrences o JOIN recurring_financial_items r ON r.id=o.recurring_id WHERE o.church_id=? AND o.period_month=? ORDER BY o.due_date",[$cid,date('Y-m')]);$cats=finance_categories($cid);$accounts=finance_accounts($cid);$funds=finance_funds($cid);$centers=finance_cost_centers($cid);
    page_top('Lançamentos recorrentes','Cadastre uma vez e o sistema lembra todos os meses');flash();
    echo '<div class="card"><h3>Nova rotina mensal</h3><form method="post">'.csrf_input().'<input type="hidden" name="action" value="create"><div class="form-grid"><div><label>Tipo</label><select name="direction"><option value="expense">Despesa</option><option value="income">Entrada</option></select></div><div><label>Categoria</label><select name="category_id" required>';foreach($cats as $c)echo '<option value="'.(int)$c['id'].'">'.e($c['name']).' · '.e($c['direction']).'</option>';echo '</select></div><div><label>Descrição</label><input name="description" required placeholder="Ex.: Energia elétrica"></div><div><label>Fornecedor</label><input name="supplier"></div><div><label>Valor previsto</label><input type="number" step="0.01" min="0" name="amount" value="0"></div><div><label>Dia de vencimento / lembrete</label><input type="number" min="1" max="31" name="due_day" value="10" required></div><div><label>Conta</label><select name="account_id"><option value="">Não definida</option>';foreach($accounts as $a)echo '<option value="'.(int)$a['id'].'">'.e($a['name']).'</option>';echo '</select></div><div><label>Fundo</label><select name="fund_id"><option value="">Não definido</option>';foreach($funds as $f)echo '<option value="'.(int)$f['id'].'">'.e($f['name']).'</option>';echo '</select></div><div><label>Centro de custo</label><select name="cost_center_id"><option value="">Não definido</option>';foreach($centers as $c)echo '<option value="'.(int)$c['id'].'">'.e($c['name']).'</option>';echo '</select></div><div><label><input type="checkbox" name="receipt_required" value="1"> Exigir comprovante</label></div></div><p><button class="btn">Criar lembrete mensal</button></p></form></div><br>';
    echo '<div class="card"><h3>Pendências de '.e(finance_month_label(date('Y-m'))).'</h3><div class="recurring-list">';if(!$occ)echo '<div class="dashboard-empty">Nenhuma rotina mensal cadastrada.</div>';foreach($occ as $o){echo '<div class="recurring-row"><div><b>'.e($o['description']).'</b><small>Vence '.e(br_date($o['due_date'])).' · '.e(money_br((float)$o['amount'])).'</small></div><span class="pill">'.e(finance_status_label($o['status'])).'</span>';if($o['status']==='pending')echo '<div class="action-row"><a class="btn" href="/?r=finance&occurrence='.(int)$o['id'].'">Lançar agora</a><form method="post">'.csrf_input().'<input type="hidden" name="action" value="skip"><input type="hidden" name="occurrence_id" value="'.(int)$o['id'].'"><button class="btn light">Não se aplica</button></form></div>';echo '</div>';}echo '</div></div><br>';
    echo '<div class="card"><h3>Rotinas cadastradas</h3><div class="table-wrap"><table class="table"><thead><tr><th>DIA</th><th>DESCRIÇÃO</th><th>TIPO</th><th>VALOR PREV.</th><th>ATIVA</th><th></th></tr></thead><tbody>';foreach($items as $i)echo '<tr><td>'.(int)$i['due_day'].'</td><td>'.e($i['description']).'</td><td>'.($i['direction']==='income'?'Entrada':'Despesa').'</td><td>'.e(money_br((float)$i['amount'])).'</td><td>'.($i['active']?'Sim':'Não').'</td><td><form method="post">'.csrf_input().'<input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="'.(int)$i['id'].'"><button class="btn light">'.($i['active']?'Desativar':'Ativar').'</button></form></td></tr>';echo '</tbody></table></div></div>';page_bottom();exit;
}

function finance_route_reconciliation(int $cid): never {
    finance_pro_guard();
    if($_SERVER['REQUEST_METHOD']==='POST'){
        verify_csrf();$action=(string)($_POST['action']??'upload');
        try{
            if($action==='upload'){
                if(empty($_FILES['statement']['tmp_name']))throw new RuntimeException('Selecione o arquivo OFX ou CSV.');
                $name=(string)$_FILES['statement']['name'];$ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));if(!in_array($ext,['ofx','csv'],true))throw new RuntimeException('Use arquivo OFX ou CSV.');
                $lines=finance_parse_statement((string)$_FILES['statement']['tmp_name'],$name);if(!$lines)throw new RuntimeException('Nenhuma movimentação reconhecida no arquivo.');
                $batch=bin2hex(random_bytes(8));$added=0;$account=(int)($_POST['account_id']??0)?:null;
                foreach($lines as $l){$key=hash('sha256',$cid.'|'.$l['key']);try{q("INSERT IGNORE INTO bank_statement_lines(church_id,account_id,import_batch,external_key,transaction_date,description,amount,status,imported_by) VALUES(?,?,?,?,?,?,?,'pending',?)",[$cid,$account,$batch,$key,$l['date'],$l['description'],$l['amount'],(int)user()['id']]);if(db()->lastInsertId())$added++;}catch(Throwable $e){}}
                audit('import_bank_statement','bank_statement',null,['file'=>$name,'rows'=>$added]);set_flash($added.' movimentação(ões) nova(s) importada(s).');
            }elseif($action==='auto_match'){
                $lines=all("SELECT * FROM bank_statement_lines WHERE church_id=? AND status='pending' ORDER BY transaction_date",[$cid]);$matched=0;
                foreach($lines as $l){$dir=(float)$l['amount']>=0?'income':'expense';$amt=abs((float)$l['amount']);$tx=one("SELECT id FROM transactions WHERE church_id=? AND status='posted' AND direction=? AND ABS(amount-?)<0.01 AND transaction_date BETWEEN DATE_SUB(?,INTERVAL 2 DAY) AND DATE_ADD(?,INTERVAL 2 DAY) AND bank_line_id IS NULL ORDER BY ABS(DATEDIFF(transaction_date,?)),id LIMIT 1",[$cid,$dir,$amt,$l['transaction_date'],$l['transaction_date'],$l['transaction_date']]);if($tx){q("UPDATE bank_statement_lines SET status='matched',matched_transaction_id=?,resolved_at=NOW() WHERE id=? AND church_id=?",[(int)$tx['id'],(int)$l['id'],$cid]);q("UPDATE transactions SET bank_line_id=? WHERE id=? AND church_id=?",[(int)$l['id'],(int)$tx['id'],$cid]);$matched++;}}
                audit('auto_reconcile_bank','bank_statement',null,['matched'=>$matched]);set_flash($matched.' movimentação(ões) conciliada(s) automaticamente.');
            }elseif($action==='match'){
                $lineId=(int)$_POST['line_id'];$txId=(int)$_POST['transaction_id'];$l=one("SELECT * FROM bank_statement_lines WHERE id=? AND church_id=? AND status='pending'",[$lineId,$cid]);$tx=one("SELECT * FROM transactions WHERE id=? AND church_id=? AND status='posted' AND bank_line_id IS NULL",[$txId,$cid]);if(!$l||!$tx)throw new RuntimeException('Movimentação não disponível para conciliação.');$dir=(float)$l['amount']>=0?'income':'expense';if($tx['direction']!==$dir||abs((float)$tx['amount']-abs((float)$l['amount']))>.01)throw new RuntimeException('Os valores/tipos não correspondem.');
                q("UPDATE bank_statement_lines SET status='matched',matched_transaction_id=?,resolved_at=NOW() WHERE id=? AND church_id=?",[$txId,$lineId,$cid]);q("UPDATE transactions SET bank_line_id=? WHERE id=? AND church_id=?",[$lineId,$txId,$cid]);audit('manual_reconcile_bank','bank_statement',$lineId,['transaction_id'=>$txId]);set_flash('Movimentação conciliada.');
            }elseif($action==='ignore'){$id=(int)$_POST['line_id'];q("UPDATE bank_statement_lines SET status='ignored',resolved_at=NOW() WHERE id=? AND church_id=? AND status='pending'",[$id,$cid]);audit('ignore_bank_line','bank_statement',$id);set_flash('Linha marcada como ignorada.');}
        }catch(Throwable $e){set_flash($e->getMessage(),'error');}
        redirect('/?r=reconciliation');
    }
    $accounts=finance_accounts($cid);$lines=all("SELECT b.*,a.name account_name FROM bank_statement_lines b LEFT JOIN accounts a ON a.id=b.account_id WHERE b.church_id=? ORDER BY FIELD(b.status,'pending','matched','ignored'),b.transaction_date DESC,b.id DESC LIMIT 250",[$cid]);
    $pending=(int)(one("SELECT COUNT(*) c FROM bank_statement_lines WHERE church_id=? AND status='pending'",[$cid])['c']??0);
    page_top('Conciliação bancária','Compare o extrato com o sistema e descubra o que ficou sem lançar');flash();
    echo '<div class="grid"><div class="card metric"><small>Linhas pendentes</small><strong class="'.($pending?'money out':'money in').'">'.$pending.'</strong></div><div class="card metric"><small>Objetivo</small><strong>0</strong><span class="metric-sub">Nada no banco sem explicação</span></div></div><br>';
    echo '<div class="card"><h3>Importar extrato</h3><form method="post" enctype="multipart/form-data">'.csrf_input().'<input type="hidden" name="action" value="upload"><div class="form-grid"><div><label>Conta bancária</label><select name="account_id"><option value="">Não definida</option>';foreach($accounts as $a)echo '<option value="'.(int)$a['id'].'">'.e($a['name']).'</option>';echo '</select></div><div><label>Arquivo</label><input type="file" name="statement" accept=".ofx,.csv" required><small class="hint">OFX é o formato recomendado. CSV também é aceito.</small></div></div><p><button class="btn">Importar extrato</button></p></form><form method="post" class="action-row">'.csrf_input().'<input type="hidden" name="action" value="auto_match"><button class="btn green">Conciliar automaticamente</button></form></div><br>';
    echo '<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>DATA</th><th>EXTRATO</th><th>VALOR</th><th>STATUS</th><th>CONCILIAR</th></tr></thead><tbody>';
    foreach($lines as $l){$amt=(float)$l['amount'];echo '<tr><td>'.e(br_date((string)$l['transaction_date'])).'</td><td>'.e($l['description']).'</td><td class="money '.($amt>=0?'in':'out').'">'.e(money_br($amt)).'</td><td><span class="pill">'.e(finance_status_label($l['status'])).'</span></td><td>';if($l['status']==='pending'){$dir=$amt>=0?'income':'expense';$cands=all("SELECT id,transaction_date,description,amount FROM transactions WHERE church_id=? AND status='posted' AND direction=? AND ABS(amount-?)<0.01 AND transaction_date BETWEEN DATE_SUB(?,INTERVAL 7 DAY) AND DATE_ADD(?,INTERVAL 7 DAY) AND bank_line_id IS NULL ORDER BY ABS(DATEDIFF(transaction_date,?)),id LIMIT 8",[$cid,$dir,abs($amt),$l['transaction_date'],$l['transaction_date'],$l['transaction_date']]);if($cands){echo '<form method="post" class="reconcile-inline">'.csrf_input().'<input type="hidden" name="action" value="match"><input type="hidden" name="line_id" value="'.(int)$l['id'].'"><select name="transaction_id">';foreach($cands as $c)echo '<option value="'.(int)$c['id'].'">#'.(int)$c['id'].' · '.e(br_date($c['transaction_date'])).' · '.e(cut_text($c['description'],32)).'</option>';echo '</select><button class="btn">Conciliar</button></form>';}else echo '<a class="btn" href="/?r=finance&bank_line='.(int)$l['id'].'">Criar lançamento</a>';echo '<form method="post" class="inline-mini">'.csrf_input().'<input type="hidden" name="action" value="ignore"><input type="hidden" name="line_id" value="'.(int)$l['id'].'"><button class="btn light">Ignorar</button></form>';}else echo '—';echo '</td></tr>';}
    echo '</tbody></table></div></div>';page_bottom();exit;
}

function finance_route_budgets(int $cid): never {
    finance_pro_guard();finance_seed_defaults($cid);$month=(string)($_GET['month']??date('Y-m'));[$from,$to,$month]=finance_month_bounds($month);
    if($_SERVER['REQUEST_METHOD']==='POST'){
        verify_csrf();$action=(string)($_POST['action']??'budget');
        try{
            if($action==='budget'){$cat=finance_category($cid,(int)$_POST['category_id']);if(!$cat)throw new RuntimeException('Categoria inválida.');q("INSERT INTO finance_budgets(church_id,year,month,direction,category_id,category,fund_id,cost_center_id,planned_amount,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)",[$cid,(int)substr($month,0,4),(int)substr($month,5,2),$cat['direction']==='both'?'expense':$cat['direction'],(int)$cat['id'],$cat['name'],(int)($_POST['fund_id']??0)?:null,(int)($_POST['cost_center_id']??0)?:null,(float)$_POST['planned_amount'],trim((string)($_POST['notes']??''))?:null,(int)user()['id']]);audit('create_budget','budget',(int)db()->lastInsertId());set_flash('Valor previsto adicionado ao orçamento.');
            }elseif($action==='fund'){$name=trim((string)$_POST['name']);if($name==='')throw new RuntimeException('Informe o nome do fundo.');q('INSERT IGNORE INTO finance_funds(church_id,name,restricted) VALUES(?,?,?)',[$cid,$name,!empty($_POST['restricted'])?1:0]);set_flash('Fundo adicionado.');
            }elseif($action==='cost'){$name=trim((string)$_POST['name']);if($name==='')throw new RuntimeException('Informe o centro de custo.');q('INSERT IGNORE INTO cost_centers(church_id,name) VALUES(?,?)',[$cid,$name]);set_flash('Centro de custo adicionado.');
            }elseif($action==='category'){$name=trim((string)$_POST['name']);$dir=in_array((string)$_POST['direction'],['income','expense','both'],true)?(string)$_POST['direction']:'expense';if($name==='')throw new RuntimeException('Informe a categoria.');q('INSERT IGNORE INTO finance_categories(church_id,name,direction,accounting_code,transparency_group) VALUES(?,?,?,?,?)',[$cid,$name,$dir,trim((string)($_POST['accounting_code']??''))?:null,trim((string)($_POST['transparency_group']??''))?:null]);set_flash('Categoria adicionada.');
            }elseif($action==='delete_budget'){q('DELETE FROM finance_budgets WHERE id=? AND church_id=?',[(int)$_POST['id'],$cid]);set_flash('Item removido do orçamento.');}
        }catch(Throwable $e){set_flash($e->getMessage(),'error');}
        redirect('/?r=budgets&month='.urlencode($month));
    }
    $budgets=all("SELECT b.*,fc.name category_name,f.name fund_name,c.name cost_center_name,(SELECT COALESCE(SUM(t.amount),0) FROM transactions t WHERE t.church_id=b.church_id AND t.status='posted' AND t.direction=b.direction AND t.transaction_date BETWEEN ? AND ? AND (t.category_id=b.category_id OR (t.category_id IS NULL AND t.category=b.category))) actual FROM finance_budgets b LEFT JOIN finance_categories fc ON fc.id=b.category_id LEFT JOIN finance_funds f ON f.id=b.fund_id LEFT JOIN cost_centers c ON c.id=b.cost_center_id WHERE b.church_id=? AND b.year=? AND b.month=? ORDER BY b.direction,b.category",[$from,$to,$cid,(int)substr($month,0,4),(int)substr($month,5,2)]);
    $cats=finance_categories($cid);$funds=finance_funds($cid);$centers=finance_cost_centers($cid);$planned=0;$actual=0;foreach($budgets as $b)if($b['direction']==='expense'){$planned+=(float)$b['planned_amount'];$actual+=(float)$b['actual'];}
    page_top('Planejamento e orçamento','Previsto x realizado · fundos, centros de custo e categorias');flash();
    echo '<div class="toolbar"><form method="get" class="month-picker"><input type="hidden" name="r" value="budgets"><label>Mês</label><input type="month" name="month" value="'.e($month).'" onchange="this.form.submit()"></form></div><div class="grid"><div class="card metric"><small>Despesas previstas</small><strong>'.e(money_br($planned)).'</strong></div><div class="card metric"><small>Despesas realizadas</small><strong class="money out">'.e(money_br($actual)).'</strong></div><div class="card metric"><small>Disponível no orçamento</small><strong>'.e(money_br($planned-$actual)).'</strong></div></div><br>';
    echo '<div class="budget-layout"><div class="card"><h3>Adicionar previsão</h3><form method="post">'.csrf_input().'<input type="hidden" name="action" value="budget"><div class="form-grid"><div><label>Categoria</label><select name="category_id">';foreach($cats as $c)echo '<option value="'.(int)$c['id'].'">'.e($c['name']).' · '.e($c['direction']).'</option>';echo '</select></div><div><label>Valor previsto</label><input type="number" step="0.01" min="0" name="planned_amount" required></div><div><label>Fundo</label><select name="fund_id"><option value="">Não definido</option>';foreach($funds as $f)echo '<option value="'.(int)$f['id'].'">'.e($f['name']).'</option>';echo '</select></div><div><label>Centro de custo</label><select name="cost_center_id"><option value="">Não definido</option>';foreach($centers as $c)echo '<option value="'.(int)$c['id'].'">'.e($c['name']).'</option>';echo '</select></div><div class="full"><label>Observação</label><input name="notes"></div></div><p><button class="btn">Adicionar ao orçamento</button></p></form></div><div class="card"><h3>Estrutura financeira</h3><details><summary>+ Novo fundo / projeto</summary><form method="post">'.csrf_input().'<input type="hidden" name="action" value="fund"><label>Nome</label><input name="name" required><label><input type="checkbox" name="restricted" value="1"> Destinação restrita</label><button class="btn">Adicionar</button></form></details><details><summary>+ Novo centro de custo</summary><form method="post">'.csrf_input().'<input type="hidden" name="action" value="cost"><label>Nome</label><input name="name" required><button class="btn">Adicionar</button></form></details><details><summary>+ Nova categoria / plano de contas</summary><form method="post">'.csrf_input().'<input type="hidden" name="action" value="category"><label>Nome</label><input name="name" required><label>Tipo</label><select name="direction"><option value="expense">Despesa</option><option value="income">Receita</option><option value="both">Ambos</option></select><label>Código contábil</label><input name="accounting_code"><label>Grupo no Portal de Transparência</label><input name="transparency_group"><button class="btn">Adicionar</button></form></details></div></div><br>';
    echo '<div class="card"><h3>Previsto x realizado</h3><div class="table-wrap"><table class="table"><thead><tr><th>CATEGORIA</th><th>TIPO</th><th>PREVISTO</th><th>REALIZADO</th><th>DIFERENÇA</th><th>USO</th></tr></thead><tbody>';foreach($budgets as $b){$pl=(float)$b['planned_amount'];$ac=(float)$b['actual'];$pct=$pl>0?min(999,($ac/$pl)*100):0;echo '<tr><td>'.e($b['category_name']?:$b['category']).'</td><td>'.($b['direction']==='income'?'Receita':'Despesa').'</td><td>'.e(money_br($pl)).'</td><td>'.e(money_br($ac)).'</td><td>'.e(money_br($pl-$ac)).'</td><td><div class="budget-bar"><i style="width:'.min(100,$pct).'%"></i></div><small>'.number_format($pct,1,',','.').'%</small></td></tr>';}if(!$budgets)echo '<tr><td colspan="6">Nenhum orçamento cadastrado neste mês.</td></tr>';echo '</tbody></table></div></div>';page_bottom();exit;
}

function finance_route_closing(int $cid): never {
    finance_pro_guard();$month=(string)($_GET['month']??date('Y-m'));[$from,$to,$month]=finance_month_bounds($month);finance_ensure_occurrences($cid,$month);$p=finance_pending_summary($cid,$month);$tot=finance_period_totals($cid,$from,$to);$closure=one("SELECT * FROM financial_period_closures WHERE church_id=? AND period_month=?",[$cid,$month]);
    if($_SERVER['REQUEST_METHOD']==='POST'){
        verify_csrf();$action=(string)($_POST['action']??'close');
        try{
            if($action==='close'){
                $p=finance_pending_summary($cid,$month);$critical=(int)$p['missing_receipts']+(int)$p['bank_pending']+(int)$p['recurring_pending']+(int)$p['overdue_payables'];if($critical>0)throw new RuntimeException('Resolva as pendências automáticas antes de fechar o mês.');
                foreach(['cash_checked','bank_checked','receipts_checked'] as $k)if(empty($_POST[$k]))throw new RuntimeException('Marque todos os itens de conferência.');
                $tot=finance_period_totals($cid,$from,$to);$check=['cash_checked'=>true,'bank_checked'=>true,'receipts_checked'=>true,'closed_from_ip'=>client_ip_hash(app_key())];
                q("INSERT INTO financial_period_closures(church_id,period_month,opening_balance,income_total,expense_total,closing_balance,checklist_json,status,closed_by,closed_at) VALUES(?,?,?,?,?,?,?,'closed',?,NOW()) ON DUPLICATE KEY UPDATE opening_balance=VALUES(opening_balance),income_total=VALUES(income_total),expense_total=VALUES(expense_total),closing_balance=VALUES(closing_balance),checklist_json=VALUES(checklist_json),status='closed',closed_by=VALUES(closed_by),closed_at=NOW(),reopened_by=NULL,reopened_at=NULL,reopen_reason=NULL",[$cid,$month,$tot['opening'],$tot['income'],$tot['expense'],$tot['closing'],json_encode($check),(int)user()['id']]);audit('close_financial_period','financial_period',null,['month'=>$month]);set_flash('Mês fechado. Novos lançamentos neste período ficam bloqueados até uma reabertura autorizada.');
            }elseif($action==='reopen'){
                if(!can_manage_users())throw new RuntimeException('Somente Pastor/Administrador pode reabrir um período.');$reason=trim((string)($_POST['reason']??''));if(strlen($reason)<8)throw new RuntimeException('Explique o motivo da reabertura.');
                q("UPDATE financial_period_closures SET status='reopened',reopened_by=?,reopened_at=NOW(),reopen_reason=? WHERE church_id=? AND period_month=?",[(int)user()['id'],$reason,$cid,$month]);audit('reopen_financial_period','financial_period',null,['month'=>$month,'reason'=>$reason]);set_flash('Período reaberto. A ação ficou registrada na auditoria.');
            }
        }catch(Throwable $e){set_flash($e->getMessage(),'error');}
        redirect('/?r=closing&month='.urlencode($month));
    }
    $closure=one("SELECT * FROM financial_period_closures WHERE church_id=? AND period_month=?",[$cid,$month]);page_top('Fechamento mensal','Checklist para terminar o mês sem lançamento esquecido');flash();
    echo '<div class="toolbar"><form method="get" class="month-picker"><input type="hidden" name="r" value="closing"><label>Mês</label><input type="month" name="month" value="'.e($month).'" onchange="this.form.submit()"></form></div><div class="grid"><div class="card metric"><small>Saldo inicial</small><strong>'.e(money_br((float)$tot['opening'])).'</strong></div><div class="card metric"><small>Entradas</small><strong class="money in">'.e(money_br((float)$tot['income'])).'</strong></div><div class="card metric"><small>Saídas</small><strong class="money out">'.e(money_br((float)$tot['expense'])).'</strong></div><div class="card metric"><small>Saldo final</small><strong>'.e(money_br((float)$tot['closing'])).'</strong></div></div><br>';
    echo '<div class="closing-layout"><div class="card"><h3>Conferência automática</h3>';foreach([['Comprovantes pendentes',$p['missing_receipts'],'finance'],['Extrato sem conciliar',$p['bank_pending'],'reconciliation'],['Recorrências pendentes',$p['recurring_pending'],'recurring'],['Contas vencidas',$p['overdue_payables'],'payables']] as $i)echo '<a class="check-row '.($i[1]?'check-bad':'check-ok').'" href="/?r='.$i[2].'"><span>'.($i[1]?'!':'✓').'</span><b>'.$i[0].'</b><strong>'.(int)$i[1].'</strong></a>';echo '</div><div class="card"><h3>Status do fechamento</h3>';
    if($closure&&$closure['status']==='closed'){echo '<div class="closed-stamp">MÊS FECHADO<small>'.e((string)$closure['closed_at']).'</small></div>';if(can_manage_users())echo '<form method="post">'.csrf_input().'<input type="hidden" name="action" value="reopen"><label>Motivo para reabrir</label><textarea name="reason" required></textarea><button class="btn danger">Reabrir período</button></form>';}else{echo '<form method="post">'.csrf_input().'<input type="hidden" name="action" value="close"><label class="check-manual"><input type="checkbox" name="cash_checked" value="1"> Conferi o caixa físico e o saldo inicial/final.</label><label class="check-manual"><input type="checkbox" name="bank_checked" value="1"> Conferi os extratos e a conciliação bancária.</label><label class="check-manual"><input type="checkbox" name="receipts_checked" value="1"> Conferi recibos, notas e comprovantes.</label><button class="btn green">Fechar mês</button></form>';}echo '</div></div>';page_bottom();exit;
}

function finance_route_needs(int $cid): never {
    finance_pro_guard();$centers=finance_cost_centers($cid);
    if($_SERVER['REQUEST_METHOD']==='POST'){
        verify_csrf();$action=(string)($_POST['action']??'create');
        try{
            if($action==='create'){q("INSERT INTO church_needs(church_id,title,description,quantity,estimated_amount,priority,cost_center_id,status,requested_by) VALUES(?,?,?,?,?,?,?,'requested',?)",[$cid,trim((string)$_POST['title']),trim((string)($_POST['description']??''))?:null,(float)($_POST['quantity']??1),(float)($_POST['estimated_amount']??0),in_array((string)($_POST['priority']??''),['low','normal','high','urgent'],true)?$_POST['priority']:'normal',(int)($_POST['cost_center_id']??0)?:null,(int)user()['id']]);audit('create_church_need','church_need',(int)db()->lastInsertId());set_flash('Necessidade registrada.');
            }elseif($action==='approve'){if(!can_manage_users())throw new RuntimeException('Somente Pastor/Administrador pode aprovar.');$id=(int)$_POST['id'];q("UPDATE church_needs SET status='approved',approved_by=?,approved_at=NOW() WHERE id=? AND church_id=? AND status='requested'",[(int)user()['id'],$id,$cid]);audit('approve_church_need','church_need',$id);set_flash('Necessidade aprovada.');
            }elseif($action==='purchased'){$id=(int)$_POST['id'];q("UPDATE church_needs SET status='purchased',purchased_at=NOW() WHERE id=? AND church_id=? AND status='approved'",[$id,$cid]);audit('purchase_church_need','church_need',$id);set_flash('Necessidade marcada como adquirida.');
            }elseif($action==='cancel'){$id=(int)$_POST['id'];q("UPDATE church_needs SET status='cancelled' WHERE id=? AND church_id=?",[$id,$cid]);audit('cancel_church_need','church_need',$id);set_flash('Necessidade cancelada.');}
        }catch(Throwable $e){set_flash($e->getMessage(),'error');}
        redirect('/?r=needs');
    }
    $rows=all("SELECT n.*,c.name cost_center_name,u.name requester FROM church_needs n LEFT JOIN cost_centers c ON c.id=n.cost_center_id LEFT JOIN users u ON u.id=n.requested_by WHERE n.church_id=? ORDER BY FIELD(n.status,'requested','approved','purchased','cancelled'),FIELD(n.priority,'urgent','high','normal','low'),n.id DESC",[$cid]);
    page_top('Necessidades da igreja','Solicitações, compras, reparos e itens que a administração precisa acompanhar');flash();
    echo '<div class="card"><h3>Registrar necessidade</h3><form method="post">'.csrf_input().'<input type="hidden" name="action" value="create"><div class="form-grid"><div><label>O que é necessário?</label><input name="title" required></div><div><label>Prioridade</label><select name="priority"><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option><option value="low">Baixa</option></select></div><div><label>Quantidade</label><input type="number" step="0.01" name="quantity" value="1"></div><div><label>Valor estimado</label><input type="number" step="0.01" min="0" name="estimated_amount" value="0"></div><div><label>Área / centro de custo</label><select name="cost_center_id"><option value="">Não definido</option>';foreach($centers as $c)echo '<option value="'.(int)$c['id'].'">'.e($c['name']).'</option>';echo '</select></div><div class="full"><label>Detalhes</label><textarea name="description"></textarea></div></div><p><button class="btn">Registrar</button></p></form></div><br>';
    echo '<div class="need-cards">';foreach($rows as $n){echo '<div class="card need-card priority-'.e($n['priority']).'"><div><span class="pill">'.e(finance_status_label($n['status'])).'</span><h3>'.e($n['title']).'</h3><p>'.e($n['description']??'').'</p><small>'.e($n['cost_center_name']??'Sem área').' · Estimativa '.e(money_br((float)$n['estimated_amount'])).'</small></div><div class="action-row">';if($n['status']==='requested'&&can_manage_users())echo '<form method="post">'.csrf_input().'<input type="hidden" name="action" value="approve"><input type="hidden" name="id" value="'.(int)$n['id'].'"><button class="btn green">Aprovar</button></form>';if($n['status']==='approved')echo '<form method="post">'.csrf_input().'<input type="hidden" name="action" value="purchased"><input type="hidden" name="id" value="'.(int)$n['id'].'"><button class="btn">Marcar comprada</button></form>';echo '</div></div>';}if(!$rows)echo '<div class="dashboard-empty">Nenhuma necessidade registrada.</div>';echo '</div>';page_bottom();exit;
}

function finance_route_reports(int $cid): never {
    finance_pro_guard();[$period,$from,$to,$label]=period_values((string)($_GET['period']??'month'),(string)($_GET['from']??''),(string)($_GET['to']??''));$d=finance_report_data($cid,$from,$to);$t=$d['totals'];page_top('Prestação de contas','Relatórios gerenciais, demonstrativos e exportação para contabilidade');flash();
    echo '<div class="card report-filter-card"><form method="get" class="form-grid report-filter"><input type="hidden" name="r" value="reports"><div><label>Período</label><select name="period"><option value="week" '.($period==='week'?'selected':'').'>Semanal</option><option value="month" '.($period==='month'?'selected':'').'>Mensal</option><option value="custom" '.($period==='custom'?'selected':'').'>Personalizado</option></select></div><div><label>De</label><input type="date" name="from" value="'.e($from).'"></div><div><label>Até</label><input type="date" name="to" value="'.e($to).'"></div><div class="report-buttons"><button class="btn light">Atualizar</button><a class="btn" target="_blank" href="/?r=finance-report-pdf&mode=inline&from='.e($from).'&to='.e($to).'">Imprimir / visualizar PDF</a><a class="btn green" href="/?r=accountant-export&from='.e($from).'&to='.e($to).'">Exportar para contador</a></div></form></div>';
    echo '<div class="grid report-summary"><div class="card metric"><small>Saldo inicial</small><strong>'.e(money_br((float)$t['opening'])).'</strong></div><div class="card metric"><small>Entradas</small><strong class="money in">'.e(money_br((float)$t['income'])).'</strong></div><div class="card metric"><small>Saídas</small><strong class="money out">'.e(money_br((float)$t['expense'])).'</strong></div><div class="card metric"><small>Saldo final</small><strong>'.e(money_br((float)$t['closing'])).'</strong></div></div><br>';
    echo '<div class="report-two"><div class="card"><h3>Resumo por categoria</h3><div class="table-wrap"><table class="table"><thead><tr><th>TIPO</th><th>CATEGORIA</th><th>VALOR</th></tr></thead><tbody>';foreach($d['categories'] as $c)echo '<tr><td>'.($c['direction']==='income'?'Entrada':'Saída').'</td><td>'.e($c['category']).'</td><td class="money '.($c['direction']==='income'?'in':'out').'">'.e(money_br((float)$c['total'])).'</td></tr>';echo '</tbody></table></div></div><div class="card"><h3>Conferência do período</h3>';foreach([['Comprovantes pendentes',$d['pending']['missing_receipts']],['Extrato sem conciliar',$d['pending']['bank_pending']],['Recorrências pendentes',$d['pending']['recurring_pending']],['Contas vencidas',$d['pending']['overdue_payables']]] as $x)echo '<div class="summary-line"><span>'.$x[0].'</span><b class="'.($x[1]?'text-danger':'money in').'">'.(int)$x[1].'</b></div>';echo '<div class="summary-line"><span>Fechamento mensal</span><b>'.($d['closure']&&$d['closure']['status']==='closed'?'Fechado':'Aberto').'</b></div></div></div><br>';
    echo '<div class="card"><div class="card-title-row"><div><h3>Movimentações detalhadas</h3><p class="muted">A versão em PDF inclui capa, fundos, orçamento, pendências, movimentações e assinaturas.</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>REF.</th><th>DATA</th><th>TIPO</th><th>CATEGORIA</th><th>HISTÓRICO</th><th>FUNDO</th><th>C. CUSTO</th><th>RECIBO</th><th>VALOR</th></tr></thead><tbody>';foreach(array_reverse(array_slice(array_reverse($d['moves']),0,200)) as $m){$in=$m['direction']==='income';echo '<tr><td>#'.str_pad((string)$m['id'],5,'0',STR_PAD_LEFT).'</td><td>'.e(br_date($m['transaction_date'])).'</td><td>'.($in?'Entrada':'Saída').'</td><td>'.e($m['category']).'</td><td>'.e($m['description']).'</td><td>'.e($m['fund_name']??'—').'</td><td>'.e($m['cost_center_name']??'—').'</td><td>'.($m['receipt_path']?'Sim':'—').'</td><td class="money '.($in?'in':'out').'">'.e(money_br((float)$m['amount'])).'</td></tr>';}echo '</tbody></table></div></div>';page_bottom();exit;
}

function finance_route_transparency(int $cid): never {
    finance_pro_guard();[$period,$from,$to,$label]=period_values((string)($_GET['period']??'month'),(string)($_GET['from']??''),(string)($_GET['to']??''));
    if($_SERVER['REQUEST_METHOD']==='POST'){
        verify_csrf();$action=(string)($_POST['action']??'publish');
        try{
            if($action==='publish'){
                $pf=(string)($_POST['from']??$from);$pt=(string)($_POST['to']??$to);$snap=finance_transparency_snapshot($cid,$pf,$pt);$token=bin2hex(random_bytes(24));$title=trim((string)($_POST['title']??''))?:'Prestação de contas';
                q("INSERT INTO transparency_publications(church_id,token,title,period_from,period_to,snapshot_json,active,published_by,published_at) VALUES(?,?,?,?,?,?,1,?,NOW())",[$cid,$token,$title,$pf,$pt,json_encode($snap,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),(int)user()['id']]);audit('publish_transparency','transparency',(int)db()->lastInsertId(),['from'=>$pf,'to'=>$pt]);set_flash('Prestação de contas publicada. O link pode ser compartilhado com a igreja.');
            }elseif($action==='revoke'){$id=(int)$_POST['id'];q('UPDATE transparency_publications SET active=0,revoked_at=NOW() WHERE id=? AND church_id=?',[$id,$cid]);audit('revoke_transparency','transparency',$id);set_flash('Publicação retirada do ar.');}
        }catch(Throwable $e){set_flash($e->getMessage(),'error');}
        redirect('/?r=transparency');
    }
    $snap=finance_transparency_snapshot($cid,$from,$to);$pubs=all('SELECT * FROM transparency_publications WHERE church_id=? ORDER BY id DESC LIMIT 30',[$cid]);$scheme=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';$base=$scheme.'://'.($_SERVER['HTTP_HOST']??'');
    page_top('Portal de Transparência','Publique somente dados consolidados, sem expor nomes de dizimistas ou doadores');flash();
    echo '<div class="transparency-warning"><b>Privacidade protegida</b><p>O portal público não mostra nomes de membros, doadores, dados bancários nem comprovantes. Ele apresenta totais consolidados, categorias, fundos, orçamento e necessidades aprovadas/em acompanhamento.</p></div>';
    echo '<div class="card"><div class="card-title-row"><div><h3>Publicar prestação de contas</h3><p class="muted">A publicação cria um retrato deste período. Alterações futuras no sistema não modificam o relatório já publicado.</p></div></div><form method="post">'.csrf_input().'<input type="hidden" name="action" value="publish"><div class="form-grid"><div><label>Título</label><input name="title" value="Prestação de contas '.e(date('m/Y',strtotime($from))).'"></div><div><label>De</label><input type="date" name="from" value="'.e($from).'"></div><div><label>Até</label><input type="date" name="to" value="'.e($to).'"></div></div><p><button class="btn green">Publicar no Portal de Transparência</button></p></form></div><br>';
    echo '<div class="grid"><div class="card metric"><small>Entradas</small><strong class="money in">'.e(money_br((float)$snap['totals']['income'])).'</strong></div><div class="card metric"><small>Saídas</small><strong class="money out">'.e(money_br((float)$snap['totals']['expense'])).'</strong></div><div class="card metric"><small>Saldo final</small><strong>'.e(money_br((float)$snap['totals']['closing'])).'</strong></div></div><br>';
    echo '<div class="card"><h3>Publicações</h3><div class="table-wrap"><table class="table"><thead><tr><th>TÍTULO</th><th>PERÍODO</th><th>PUBLICADO</th><th>STATUS</th><th>LINK</th></tr></thead><tbody>';foreach($pubs as $p){$url=$base.'/?r=transparency-public&token='.$p['token'];echo '<tr><td>'.e($p['title']).'</td><td>'.e(br_date($p['period_from'])).' a '.e(br_date($p['period_to'])).'</td><td>'.e($p['published_at']).'</td><td><span class="pill">'.($p['active']?'Publicado':'Encerrado').'</span></td><td>';if($p['active'])echo '<a class="btn light" target="_blank" href="'.e($url).'">Abrir portal</a> <input class="share-link" readonly value="'.e($url).'" onclick="this.select()">';else echo '—';echo '</td></tr>';}if(!$pubs)echo '<tr><td colspan="5">Nenhuma prestação de contas publicada.</td></tr>';echo '</tbody></table></div></div>';page_bottom();exit;
}

function finance_route_export(int $cid): never {
    finance_pro_guard();$from=(string)($_GET['from']??date('Y-m-01'));$to=(string)($_GET['to']??date('Y-m-t'));
    $rows=all("SELECT t.id,t.transaction_date,t.direction,fc.accounting_code,t.category,t.description,t.supplier,t.document_number,t.payment_method,t.amount,a.name account_name,f.name fund_name,c.name cost_center_name,t.status FROM transactions t LEFT JOIN finance_categories fc ON fc.id=t.category_id LEFT JOIN accounts a ON a.id=t.account_id LEFT JOIN finance_funds f ON f.id=t.fund_id LEFT JOIN cost_centers c ON c.id=t.cost_center_id WHERE t.church_id=? AND t.transaction_date BETWEEN ? AND ? ORDER BY t.transaction_date,t.id",[$cid,$from,$to]);
    audit('export_accounting_csv','report',null,['from'=>$from,'to'=>$to]);header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="Exportacao-Contador-'.$from.'-'.$to.'.csv"');echo "\xEF\xBB\xBF";$o=fopen('php://output','wb');fputcsv($o,['Referência','Data','Tipo','Código contábil','Categoria','Histórico','Fornecedor','Documento','Forma pagamento','Conta','Fundo','Centro de custo','Valor','Status'],';');foreach($rows as $r)fputcsv($o,['#'.str_pad((string)$r['id'],6,'0',STR_PAD_LEFT),$r['transaction_date'],$r['direction']==='income'?'Receita':'Despesa',$r['accounting_code'],$r['category'],$r['description'],$r['supplier'],$r['document_number'],$r['payment_method'],$r['account_name'],$r['fund_name'],$r['cost_center_name'],number_format((float)$r['amount'],2,',',''),$r['status']],';');fclose($o);exit;
}

function finance_pro_handle(string $route,int $cid): void {
    $routes=['treasury','finance','payables','recurring','reconciliation','budgets','closing','needs','reports','finance-report-pdf','accountant-export','transparency'];
    if(!in_array($route,$routes,true))return;
    finance_seed_defaults($cid);
    if($route==='treasury')finance_route_treasury($cid);
    if($route==='finance')finance_route_finance($cid);
    if($route==='payables')finance_route_payables($cid);
    if($route==='recurring')finance_route_recurring($cid);
    if($route==='reconciliation')finance_route_reconciliation($cid);
    if($route==='budgets')finance_route_budgets($cid);
    if($route==='closing')finance_route_closing($cid);
    if($route==='needs')finance_route_needs($cid);
    if($route==='reports')finance_route_reports($cid);
    if($route==='finance-report-pdf'){finance_pro_guard();$from=(string)($_GET['from']??date('Y-m-01'));$to=(string)($_GET['to']??date('Y-m-t'));finance_pdf_report($cid,$from,$to,(string)($_GET['mode']??'attachment'));}
    if($route==='accountant-export')finance_route_export($cid);
    if($route==='transparency')finance_route_transparency($cid);
}
