<?php
if(session_status()!==PHP_SESSION_ACTIVE){session_start();}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Igreja Master · Sistema de Gestão</title><meta name="description" content="Gestão completa para igrejas com membros, secretaria, eventos, PIX, WhatsApp, documentos, relatórios e automações."><link rel="stylesheet" href="/assets/public.css?v=1"></head><body>
<header class="public-header"><div class="container public-nav"><a class="brand" href="/"><span class="brand-mark">✦</span><span>Igreja Master</span></a><div class="nav-actions"><a class="btn btn-ghost" href="/login">Entrar</a><a class="btn btn-primary" href="/pricing#contato">Começar</a></div></div></header>
<section class="hero"><div class="container hero-inner"><span class="eyebrow">Plataforma completa para gestão e comunicação da igreja</span><h1>Organize a igreja e aproxime as pessoas com uma gestão <span>simples e moderna</span></h1><p>Centralize membros, congregações, eventos, secretaria, PIX, documentos, relatórios, WhatsApp, oração e automações em um único sistema.</p><div class="hero-actions"><a class="btn btn-primary" href="/pricing#contato">Conhecer os planos →</a><a class="btn btn-ghost" style="color:white;border:1px solid #ffffff33" href="/login">Já tenho acesso</a></div><div class="kpis"><div class="kpi"><strong>24/7</strong><span>Bot WhatsApp</span></div><div class="kpi"><strong>1 painel</strong><span>Secretaria e gestão</span></div><div class="kpi"><strong>Multi</strong><span>Igrejas e congregações</span></div><div class="kpi"><strong>Automático</strong><span>Lembretes e rotinas</span></div></div></div></section>
<section class="section alt"><div class="container"><div class="section-head"><h2>Tudo que sua igreja precisa em um só lugar</h2><p>Recursos integrados para reduzir trabalho manual e melhorar a organização da secretaria, liderança e comunicação.</p></div><div class="feature-grid">
<article class="feature"><div class="feature-icon">💬</div><h3>WhatsApp inteligente</h3><p>Menu automático, cadastro de membros, pedidos de oração, eventos, rifas, relógio de oração e respostas assistidas por IA.</p></article>
<article class="feature"><div class="feature-icon">👥</div><h3>Gestão de membros</h3><p>Cadastro completo, congregações, perfil, fotos, dados de batismo, cargos, departamentos e documentos oficiais.</p></article>
<article class="feature"><div class="feature-icon">📅</div><h3>Eventos e cultos</h3><p>Agenda, tipos de culto, inscrições, lembretes automáticos e geração de cartazes por IA.</p></article>
<article class="feature"><div class="feature-icon">💠</div><h3>PIX e contribuições</h3><p>Acompanhe movimentações PIX, finalidades e relatórios por período e congregação.</p></article>
<article class="feature"><div class="feature-icon">📄</div><h3>Documentos verificáveis</h3><p>Carteirinha, certificados, cartas e declarações com código real de autenticidade registrado no banco.</p></article>
<article class="feature"><div class="feature-icon">📊</div><h3>Relatórios e transparência</h3><p>Indicadores, movimentações e relatórios prontos para impressão e prestação de contas.</p></article>
</div></div></section>
<section class="section"><div class="container"><div class="section-head"><h2>Feito para facilitar o trabalho da igreja</h2><p>Menos tarefas esquecidas, menos planilhas espalhadas e mais histórico centralizado.</p></div><div class="benefits"><div class="benefit"><span class="check">✓</span><span>Cadastro público por link e pelo WhatsApp</span></div><div class="benefit"><span class="check">✓</span><span>Lembretes automáticos para eventos e oração</span></div><div class="benefit"><span class="check">✓</span><span>Devocional e plano de leitura bíblica</span></div><div class="benefit"><span class="check">✓</span><span>Rifas e enquetes integradas</span></div><div class="benefit"><span class="check">✓</span><span>Moderação de grupos e histórico de logs</span></div><div class="benefit"><span class="check">✓</span><span>Atualização automática e backup de segurança</span></div></div><div style="text-align:center;margin-top:38px"><a class="btn btn-primary" href="/pricing">Ver planos e recursos</a></div></div></section>
<footer class="footer"><div class="container footer-inner"><strong>Igreja Master · Sistema de Gestão</strong><div><a href="/pricing">Planos</a> · <a href="/verify">Verificar documento</a> · <a href="/login">Entrar</a></div></div></footer></body></html>