<?php
require __DIR__.'/bootstrap.php';
$auth->requireAbility('secretary');$church=$auth->currentChurch();if(!$church)redirect('logout.php');$cid=$church['id'];$id=trim($_GET['id']??'');
$q=$pdo->prepare('SELECT m.*,c.name congregation_name,c.address congregation_address,c.pastor_name congregation_pastor,c.pastor_signature_url congregation_signature FROM members m LEFT JOIN congregations c ON c.id=m.congregation_id WHERE m.id=? AND m.church_id=? LIMIT 1');$q->execute([$id,$cid]);$m=$q->fetch();if(!$m){http_response_code(404);exit('Membro não encontrado.');}
function fmt_date(?string $d):string{return $d?date('d/m/Y',strtotime($d)):'—';}
$address=implode(', ',array_filter([$m['address_street']??null,$m['address_number']??null,$m['address_neighborhood']??null,$m['address_city']??null,$m['address_state']??null]));
View::header('Perfil do Membro',$auth,'members.php');
?>
<div class="card card-pad"><div class="page-head"><div><a class="btn btn-light" href="members.php">← Voltar</a><h1 style="margin-top:12px"><?=e($m['name'])?></h1><p><?=e($m['role']?:'Membro')?> · <?=e($m['congregation_name']?:'Sede/Não informada')?></p></div><?php if($m['photo_url']):?><img src="<?=e($m['photo_url'])?>" alt="" style="width:110px;height:110px;border-radius:22px;object-fit:cover"><?php endif?></div>
<div class="grid two-col"><section><h3>Contato e dados pessoais</h3><p><strong>Telefone:</strong> <?=e($m['phone'])?></p><p><strong>E-mail:</strong> <?=e($m['email']?:'—')?></p><p><strong>Nascimento:</strong> <?=e(fmt_date($m['birth_date']))?></p><p><strong>CPF:</strong> <?=e($m['cpf']?:'—')?> &nbsp; <strong>RG:</strong> <?=e($m['rg']?:'—')?></p><p><strong>Estado civil:</strong> <?=e($m['marital_status']?:'—')?></p><p><strong>Cônjuge:</strong> <?=e($m['spouse_name']?:'—')?></p><p><strong>Pai:</strong> <?=e($m['father_name']?:'—')?></p><p><strong>Mãe:</strong> <?=e($m['mother_name']?:'—')?></p><p><strong>Naturalidade:</strong> <?=e($m['naturalness']?:'—')?> &nbsp; <strong>Nacionalidade:</strong> <?=e($m['nationality']?:'—')?></p><p><strong>Endereço:</strong> <?=e($address?:'—')?></p></section><section><h3>Vida na igreja</h3><p><strong>Membro desde:</strong> <?=e(fmt_date($m['membership_date']))?></p><p><strong>Tempo de igreja:</strong> <?=e($m['church_time']?:'—')?></p><p><strong>Cargo/Função:</strong> <?=e($m['role']?:'—')?></p><p><strong>Departamento:</strong> <?=e($m['department']?:'—')?></p><p><strong>Batizado:</strong> <?=$m['is_baptized']?'Sim':'Não'?></p><p><strong>Data do batismo:</strong> <?=e(fmt_date($m['baptism_date']))?></p><p><strong>Igreja do batismo:</strong> <?=e($m['baptism_church']?:'—')?></p><p><strong>Pastor do batismo:</strong> <?=e($m['baptism_pastor']?:'—')?></p><p><strong>Status:</strong> <span class="badge <?=$m['active']?'ok':'off'?>"><?=$m['active']?'Ativo':'Inativo'?></span></p></section></div>
<div class="actions"><a class="btn btn-primary" href="members.php?edit=<?=e($m['id'])?>#cadastro">Editar cadastro</a><a class="btn btn-light" target="_blank" href="https://wa.me/<?=e(preg_replace('/\D+/','',$m['phone']))?>">WhatsApp</a></div></div>
<section class="card card-pad"><div class="page-head"><div><h2>Documentos do membro</h2><p>Gerar, visualizar e imprimir documentos oficiais.</p></div></div><div class="grid two-col">
<?php $docs=['baptism_certificate'=>['Certificado de Batismo','Documento oficial de batismo nas águas'],'membership_card'=>['Carteirinha de Membro','Identificação do membro'],'membership_certificate'=>['Certificado de Membro','Comprovação de membresia ativa'],'recommendation_letter'=>['Carta de Recomendação','Para transferência de igreja'],'dismissal_letter'=>['Carta de Desligamento','Documento de saída da igreja'],'visitor_presentation'=>['Carta de Apresentação','Apresentação e acolhimento'],'attendance_declaration'=>['Declaração de Frequência','Comprova participação regular']];foreach($docs as $type=>$d):?><a class="card card-pad" style="text-decoration:none" target="_blank" href="member-document.php?id=<?=e($m['id'])?>&type=<?=e($type)?>"><strong><?=e($d[0])?></strong><p><?=e($d[1])?></p><span class="btn btn-light">Abrir documento</span></a><?php endforeach?></div></section>
<?php View::footer();