<?php
require __DIR__.'/bootstrap.php';
$auth->requireAbility('secretary');$user=$auth->user();$church=$auth->currentChurch();if(!$church)redirect('logout.php');$cid=$church['id'];$id=trim($_GET['id']??'');$type=trim($_GET['type']??'');
$allowed=['baptism_certificate','membership_card','membership_certificate','recommendation_letter','dismissal_letter','visitor_presentation','attendance_declaration'];if(!in_array($type,$allowed,true)){http_response_code(400);exit('Documento inválido.');}
$q=$pdo->prepare('SELECT m.*,c.name congregation_name,c.address congregation_address,c.pastor_name congregation_pastor,c.pastor_signature_url congregation_signature FROM members m LEFT JOIN congregations c ON c.id=m.congregation_id WHERE m.id=? AND m.church_id=? LIMIT 1');$q->execute([$id,$cid]);$m=$q->fetch();if(!$m){http_response_code(404);exit('Membro não encontrado.');}
$prefixes=['baptism_certificate'=>'BAP','membership_card'=>'CAR','membership_certificate'=>'MEM','recommendation_letter'=>'REC','dismissal_letter'=>'DIS','visitor_presentation'=>'VIS','attendance_declaration'=>'FRE'];
$q=$pdo->prepare('SELECT verification_code FROM issued_documents WHERE church_id=? AND member_id=? AND document_type=? AND revoked_at IS NULL ORDER BY issued_at DESC LIMIT 1');$q->execute([$cid,$id,$type]);$verification=$q->fetchColumn();
if(!$verification){$memberCode=strtoupper(substr(str_replace('-','',$id),0,6));$churchCode=strtoupper(substr(str_replace('-','',$cid),0,6));$verification=$prefixes[$type].'-'.$memberCode.'-'.$churchCode.'-'.strtoupper(substr(bin2hex(random_bytes(5)),0,10));$pdo->prepare('INSERT INTO issued_documents(id,church_id,member_id,document_type,verification_code,issued_by,metadata) VALUES(?,?,?,?,?,?,?)')->execute([app_uuid(),$cid,$id,$type,$verification,$user['id']??null,json_encode(['member_name'=>$m['name'],'church_name'=>$church['name']],JSON_UNESCAPED_UNICODE)]);}
$pastor=$m['congregation_pastor']?:($church['pastor_name']??'');$address=$m['congregation_address']?:($church['address']??'');$today=date('d/m/Y');$fmt=fn($d)=>$d?date('d/m/Y',strtotime($d)):'_______________';
$title='Documento';$body='';
switch($type){
case 'baptism_certificate':$title='Certificado de Batismo';$body="Certificamos que <strong>".e($m['name'])."</strong>, nascido(a) em ".e($fmt($m['birth_date'])).", foi batizado(a) nas águas em <strong>".e($fmt($m['baptism_date']))."</strong>, na igreja ".e($m['baptism_church']?:$church['name']).", pelo Pastor ".e($m['baptism_pastor']?:$pastor).".";break;
case 'membership_card':$title='Carteira de Membro';$body="<strong>".e($m['name'])."</strong><br>CPF: ".e($m['cpf']?:'_______________')."<br>Membro desde: ".e($fmt($m['membership_date']))."<br>Cargo/Função: ".e($m['role']?:'Membro')."<br>Departamento: ".e($m['department']?:'—')."<br>Batizado(a): ".($m['is_baptized']?'Sim':'Não');break;
case 'membership_certificate':$title='Certificado de Membro';$body="Certificamos, para os devidos fins, que <strong>".e($m['name'])."</strong> é membro ativo desta igreja desde <strong>".e($fmt($m['membership_date']))."</strong>, participando das atividades eclesiásticas, exercendo a função de ".e($m['role']?:'membro').".";break;
case 'recommendation_letter':$title='Carta de Recomendação';$body="A Paz do Senhor! Pela presente, recomendamos o(a) irmão(ã) <strong>".e($m['name'])."</strong>, membro desta igreja desde ".e($fmt($m['membership_date'])).", de bom testemunho e conduta cristã, para que seja recebido(a) com amor fraternal.";break;
case 'dismissal_letter':$title='Carta de Desligamento';$body="Declaramos que o(a) irmão(ã) <strong>".e($m['name'])."</strong>, membro desta igreja desde ".e($fmt($m['membership_date'])).", solicita seu desligamento nesta data, ficando livre para congregar em outra comunidade de fé.";break;
case 'visitor_presentation':$title='Carta de Apresentação';$body="É com alegria que apresentamos <strong>".e($m['name'])."</strong>. Desejamos que seja recebido(a) com amor e comunhão cristã.";break;
case 'attendance_declaration':$title='Declaração de Frequência';$body="Declaramos, para os devidos fins, que <strong>".e($m['name'])."</strong> é membro ativo desta igreja desde ".e($fmt($m['membership_date']))." e frequenta regularmente os cultos e atividades eclesiásticas.";break;}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?></title><style>body{font-family:Arial,sans-serif;background:#f3f5f8;margin:0;padding:24px;color:#1c2430}.sheet{max-width:820px;margin:auto;background:white;padding:64px;min-height:980px;box-shadow:0 8px 30px #0002}.head{text-align:center;border-bottom:2px solid #222;padding-bottom:24px;margin-bottom:54px}.logo{max-width:90px;max-height:90px;border-radius:18px}.head h1{font-size:24px;margin:12px 0 4px}.doc-title{text-align:center;text-transform:uppercase;font-size:28px;letter-spacing:1px;margin:0 0 50px}.body{font-size:18px;line-height:1.9;text-align:justify}.footer{margin-top:100px;text-align:center}.signature{margin:80px auto 0;border-top:1px solid #333;width:320px;padding-top:8px}.verify{margin-top:50px;border:1px solid #ccd3dd;background:#f8fafc;padding:14px;text-align:center;font-size:12px}.actions{max-width:820px;margin:16px auto;text-align:right}.btn{padding:10px 16px;border:0;border-radius:8px;background:#1f6feb;color:white;cursor:pointer}@media print{body{background:white;padding:0}.sheet{box-shadow:none;max-width:none;min-height:auto}.actions{display:none}}</style></head><body><div class="actions"><button class="btn" onclick="window.print()">Imprimir / Salvar PDF</button></div><article class="sheet"><div class="head"><?php if(!empty($church['logo_url'])):?><img class="logo" src="<?=e($church['logo_url'])?>"><?php endif?><h1><?=e($church['name'])?></h1><div><?=e($address)?></div></div><h2 class="doc-title"><?=e($title)?></h2><div class="body"><?=$body?></div><div class="footer"><p><?=e($today)?></p><div class="signature"><?=e($pastor?:'Responsável / Pastor')?></div><div class="verify"><strong>Verificação de autenticidade</strong><br>Código: <strong><?=e($verification)?></strong><br>Acesse <strong>/verify.php?code=<?=e($verification)?></strong></div></div></article></body></html>