<?php
require __DIR__.'/bootstrap.php';
$sent=false;$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        verify_csrf();
        $name=trim((string)($_POST['name']??''));
        $email=trim((string)($_POST['email']??''));
        $message=trim((string)($_POST['message']??''));
        if($name===''||$message===''||!filter_var($email,FILTER_VALIDATE_EMAIL)) throw new RuntimeException('Preencha nome, e-mail válido e mensagem.');
        $ipHash=hash('sha256',(string)($_SERVER['REMOTE_ADDR']??'').'|'.date('Y-m-d'));
        $q=$pdo->prepare('INSERT INTO contact_leads(id,name,email,phone,church_name,members_count,plan,message,status,source,ip_hash) VALUES(?,?,?,?,?,?,?,?,"new","pricing",?)');
        $q->execute([app_uuid(),$name,$email,null_if_blank($_POST['phone']??null),null_if_blank($_POST['church_name']??null),null_if_blank($_POST['members_count']??null),null_if_blank($_POST['plan']??null),$message,$ipHash]);
        $sent=true;
    }catch(Throwable $e){$error=$e->getMessage();}
}
$plans=[
 ['name'=>'Básico','price'=>'R$ 97','desc'=>'Ideal para igrejas pequenas que estão começando','popular'=>false,'items'=>['Bot WhatsApp básico','Até 200 membros','PIX automático','Pedidos de oração','1 congregação','Relatórios básicos','Suporte por e-mail']],
 ['name'=>'Pro','price'=>'R$ 197','desc'=>'Para igrejas em crescimento que precisam de mais recursos','popular'=>true,'items'=>['Bot WhatsApp avançado','Até 1.000 membros','PIX automático','Pedidos de oração com IA','Até 5 congregações','Eventos ilimitados','Documentos personalizados','Relatórios completos','Suporte por WhatsApp']],
 ['name'=>'Enterprise','price'=>'R$ 397','desc'=>'Solução completa para ministérios e denominações','popular'=>false,'items'=>['Bot WhatsApp ampliado','Membros ilimitados','Congregações ilimitadas','IA e automações avançadas','Eventos ilimitados','Documentos personalizados','API de integração','Relatórios avançados','Suporte prioritário']],
];
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Planos · Igreja Master</title><meta name="description" content="Planos do Igreja Master para gestão de membros, secretaria, eventos, PIX, WhatsApp e automações."><link rel="stylesheet" href="/assets/public.css?v=1"></head><body>
<header class="public-header"><div class="container public-nav"><a class="brand" href="/"><span class="brand-mark">✦</span><span>Igreja Master</span></a><div class="nav-actions"><a class="btn btn-ghost" href="/login">Entrar</a><a class="btn btn-primary" href="#contato">Começar</a></div></div></header>
<section class="hero"><div class="container hero-inner"><span class="eyebrow">Planos flexíveis para cada fase da igreja</span><h1>Escolha um plano que acompanhe o <span>crescimento da sua igreja</span></h1><p>Gestão de membros, secretaria, eventos, WhatsApp, PIX, documentos, relatórios e automações em uma plataforma integrada.</p></div></section>
<section class="section"><div class="container"><div class="plan-grid"><?php foreach($plans as $p):?><article class="plan <?=$p['popular']?'popular':''?>"><?php if($p['popular']):?><span class="popular-badge">Mais escolhido</span><?php endif?><h3><?=e($p['name'])?></h3><p style="color:#64748b"><?=e($p['desc'])?></p><div class="price"><?=e($p['price'])?> <small>/mês</small></div><ul><?php foreach($p['items'] as $item):?><li><span class="check">✓</span><?=e($item)?></li><?php endforeach?></ul><a class="btn <?=$p['popular']?'btn-primary':'btn-dark'?>" href="#contato" data-plan="<?=e($p['name'])?>">Tenho interesse</a></article><?php endforeach?></div></div></section>
<section class="section alt" id="contato"><div class="container contact-wrap"><div><span class="eyebrow" style="color:#334155;border-color:#dbe3ec;background:#fff">Fale com a equipe</span><h2 style="font-size:40px;margin:18px 0 12px">Quer conhecer o sistema?</h2><p style="color:#64748b;line-height:1.75">Envie seus dados. O contato fica registrado no painel para acompanhamento comercial e implantação.</p><div class="benefits" style="grid-template-columns:1fr;margin-top:26px"><div class="benefit"><span class="check">✓</span><span>Implantação orientada</span></div><div class="benefit"><span class="check">✓</span><span>Estrutura multi-igreja e congregações</span></div><div class="benefit"><span class="check">✓</span><span>Atualizações automáticas do sistema</span></div></div></div><form class="contact-card" method="post"><?=csrf_field()?><?php if($sent):?><div class="alert alert-ok">Mensagem enviada com sucesso. Entraremos em contato.</div><?php endif?><?php if($error):?><div class="alert alert-error"><?=e($error)?></div><?php endif?><div class="form-grid"><div class="field"><label>Nome *</label><input class="input" name="name" required value="<?=e($_POST['name']??'')?>"></div><div class="field"><label>E-mail *</label><input class="input" type="email" name="email" required value="<?=e($_POST['email']??'')?>"></div><div class="field"><label>Telefone</label><input class="input" name="phone" value="<?=e($_POST['phone']??'')?>"></div><div class="field"><label>Nome da igreja</label><input class="input" name="church_name" value="<?=e($_POST['church_name']??'')?>"></div><div class="field"><label>Quantidade de membros</label><select class="select" name="members_count"><option value="">Selecione</option><option>Até 200</option><option>201 a 1.000</option><option>1.001 a 5.000</option><option>Mais de 5.000</option></select></div><div class="field"><label>Plano de interesse</label><select class="select" id="plan" name="plan"><option value="">Ainda não sei</option><option>Básico</option><option>Pro</option><option>Enterprise</option></select></div><div class="field full"><label>Mensagem *</label><textarea class="textarea" name="message" required><?=e($_POST['message']??'Quero conhecer melhor o Igreja Master e receber informações para implantação.')?></textarea></div></div><button class="btn btn-primary" style="width:100%;margin-top:16px">Enviar interesse</button></form></div></section>
<footer class="footer"><div class="container footer-inner"><strong>Igreja Master · Sistema de Gestão</strong><div><a href="/">Início</a> · <a href="/login">Entrar</a></div></div></footer>
<script>document.querySelectorAll('[data-plan]').forEach(a=>a.addEventListener('click',()=>{const s=document.getElementById('plan');if(s)s.value=a.dataset.plan||'';}));</script></body></html>