<?php
require __DIR__.'/bootstrap.php';
$slug=trim((string)($_GET['slug']??''));
if($slug===''){http_response_code(404);exit('Portal não encontrado.');}
$q=$pdo->prepare('SELECT id,name,slug,logo_url,address,transparency_enabled FROM churches WHERE slug=? AND active=1 LIMIT 1');$q->execute([$slug]);$church=$q->fetch();
if(!$church||empty($church['transparency_enabled'])){http_response_code(404);exit('Portal de transparência não disponível.');}
$cid=$church['id'];$month=(string)($_GET['month']??date('Y-m'));if(!preg_match('/^\d{4}-\d{2}$/',$month))$month=date('Y-m');
$dt=DateTimeImmutable::createFromFormat('!Y-m',$month)?:new DateTimeImmutable('first day of this month');$from=$dt->format('Y-m-01');$to=$dt->format('Y-m-t');
$q=$pdo->prepare("SELECT COALESCE(SUM(CASE WHEN direction='income' AND status='posted' THEN amount ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN direction='expense' AND status='posted' THEN amount ELSE 0 END),0) expense FROM finance_entries WHERE church_id=? AND transaction_date BETWEEN ? AND ?");$q->execute([$cid,$from,$to]);$tot=$q->fetch()?:['income'=>0,'expense'=>0];
$q=$pdo->prepare("SELECT COALESCE(SUM(opening_balance),0) FROM finance_accounts WHERE church_id=? AND active=1");$q->execute([$cid]);$opening=(float)$q->fetchColumn();
$q=$pdo->prepare("SELECT COALESCE(SUM(CASE WHEN direction='income' AND status='posted' THEN amount WHEN direction='expense' AND status='posted' THEN -amount ELSE 0 END),0) FROM finance_entries WHERE church_id=? AND transaction_date<?");$q->execute([$cid,$from]);$opening+=(float)$q->fetchColumn();
$income=(float)$tot['income'];$expense=(float)$tot['expense'];$closing=$opening+$income-$expense;
$q=$pdo->prepare("SELECT direction,category,SUM(amount) total FROM finance_entries WHERE church_id=? AND status='posted' AND transaction_date BETWEEN ? AND ? GROUP BY direction,category ORDER BY direction,total DESC");$q->execute([$cid,$from,$to]);$categories=$q->fetchAll();
$q=$pdo->prepare("SELECT category,planned_amount FROM finance_budgets WHERE church_id=? AND year=? AND month=? ORDER BY category");$q->execute([$cid,(int)$dt->format('Y'),(int)$dt->format('n')]);$budgets=$q->fetchAll();
$q=$pdo->prepare("SELECT title,description,quantity,estimated_amount,priority,status FROM church_needs WHERE church_id=? AND status IN('requested','approved') ORDER BY FIELD(priority,'urgent','high','normal','low'),created_at DESC LIMIT 40");$q->execute([$cid]);$needs=$q->fetchAll();
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Transparência · <?=e($church['name'])?></title><link rel="stylesheet" href="/assets/public.css?v=1"><style>.trans{padding:38px 0}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.sum,.public-card{background:#fff;border:1px solid #e5eaf1;border-radius:18px}.sum{padding:20px}.sum span{display:block;color:#64748b;font-size:12px}.sum strong{font-size:25px}.public-card{padding:24px;margin-top:18px}.table-public{width:100%;border-collapse:collapse}.table-public th,.table-public td{padding:12px;border-bottom:1px solid #e8edf3;text-align:left}.table-public th{font-size:12px;color:#64748b}@media(max-width:720px){.summary{grid-template-columns:1fr 1fr}}</style></head><body>
<header class="public-header"><div class="container public-nav"><div class="brand"><span class="brand-mark">✦</span><span><?=e($church['name'])?></span></div><strong>Portal de Transparência</strong></div></header>
<main class="container trans"><div class="section-head"><h1>Prestação de contas</h1><p>Informações financeiras agregadas. Nenhum dado pessoal de membros é publicado.</p><form method="get" style="margin-top:16px"><input type="hidden" name="slug" value="<?=e($slug)?>"><input class="input" style="max-width:210px;display:inline-block" type="month" name="month" value="<?=e($month)?>"><button class="btn btn-primary">Ver período</button></form></div>
<div class="summary"><div class="sum"><span>Saldo inicial</span><strong>R$ <?=number_format($opening,2,',','.')?></strong></div><div class="sum"><span>Entradas</span><strong>R$ <?=number_format($income,2,',','.')?></strong></div><div class="sum"><span>Saídas</span><strong>R$ <?=number_format($expense,2,',','.')?></strong></div><div class="sum"><span>Saldo final</span><strong>R$ <?=number_format($closing,2,',','.')?></strong></div></div>
<section class="public-card"><h2>Movimentação por categoria</h2><table class="table-public"><thead><tr><th>Tipo</th><th>Categoria</th><th>Total</th></tr></thead><tbody><?php foreach($categories as $r):?><tr><td><?=e($r['direction']==='income'?'Entrada':'Saída')?></td><td><?=e($r['category'])?></td><td>R$ <?=number_format((float)$r['total'],2,',','.')?></td></tr><?php endforeach?></tbody></table></section>
<?php if($budgets):?><section class="public-card"><h2>Planejamento do mês</h2><table class="table-public"><thead><tr><th>Categoria</th><th>Valor planejado</th></tr></thead><tbody><?php foreach($budgets as $b):?><tr><td><?=e($b['category'])?></td><td>R$ <?=number_format((float)$b['planned_amount'],2,',','.')?></td></tr><?php endforeach?></tbody></table></section><?php endif?>
<?php if($needs):?><section class="public-card"><h2>Necessidades e projetos</h2><table class="table-public"><thead><tr><th>Necessidade</th><th>Prioridade</th><th>Quantidade</th><th>Estimativa</th></tr></thead><tbody><?php foreach($needs as $n):?><tr><td><strong><?=e($n['title'])?></strong><?php if($n['description']):?><div style="color:#64748b"><?=e($n['description'])?></div><?php endif?></td><td><?=e(ucfirst($n['priority']))?></td><td><?=e((string)$n['quantity'])?></td><td>R$ <?=number_format((float)$n['estimated_amount'],2,',','.')?></td></tr><?php endforeach?></tbody></table></section><?php endif?>
<p style="text-align:center;color:#64748b;margin-top:30px">Período: <?=date('d/m/Y',strtotime($from))?> a <?=date('d/m/Y',strtotime($to))?> · Demonstrativo administrativo/gerencial.</p></main></body></html>